import {
  CAPABILITIES_SCHEMA_VERSION,
  CLI_NAME,
  EXPECTED_BINARY_NAME,
  GENERATOR_NAME,
  GENERATOR_VERSION,
} from './metadata.js';

export const CAPABILITIES_CONTRACT = {
  schemaVersion: CAPABILITIES_SCHEMA_VERSION,
  generator: {
    packageName: GENERATOR_NAME,
    packageVersion: GENERATOR_VERSION,
    cliName: CLI_NAME,
    binary: EXPECTED_BINARY_NAME,
  },
  productBoundary: {
    cliRole: 'deterministic-scriptable-capability-layer',
    agentRole: 'intelligent-planner',
    sourceAuthority: 'agent-owned',
    taskFit: 'agent-owned',
    sourceSelection: 'agent-owned-explicit-decision',
    discoveryReports: 'candidate-evidence-not-source-selection',
    statement:
      'The CLI accepts explicit inputs and reports deterministic facts. The agent owns source authority, task fit, and selected source decisions.',
  },
  implemented: [
    {
      id: 'discover-source',
      command: 'discover',
      mode: 'discover --source',
      status: 'implemented',
      inputBoundary: 'explicit local file or directory',
      outputFiles: ['discovery-report.json', 'manifest.json'],
      summary:
        'bounded local source inspection with deterministic candidate file evidence, descriptive manifest contract metadata, content-free input provenance summary metadata, content-free artifact summary metadata, and a compact content-free candidate evidence manifest index',
      limitations: [
        'candidate evidence for agent review only',
        'input provenance summaries are content-free candidate-evidence metadata only',
        'artifact summaries are content-free manifest metadata only',
        'candidate evidence index is manifest metadata only',
        'no docs generation',
        'no source selection',
        'no trust scoring',
      ],
    },
    {
      id: 'discover-repo',
      command: 'discover',
      mode: 'discover --repo',
      status: 'implemented',
      inputBoundary: 'explicit git URL or explicit local git repository',
      options: ['--scope <path>', '--cache-dir <dir>', '--output-dir <dir>'],
      outputFiles: ['discovery-report.json', 'manifest.json'],
      summary:
        'bounded repository inspection with stable cache reuse, optional repo-relative scope, descriptive manifest contract metadata, content-free input provenance summary metadata, content-free artifact summary metadata, and a compact content-free candidate evidence manifest index',
      limitations: [
        'candidate evidence for agent review only',
        'input provenance summaries are content-free candidate-evidence metadata only',
        'artifact summaries are content-free manifest metadata only',
        'candidate evidence index is manifest metadata only',
        'no repo script execution',
        'no docs generation',
        'no source selection',
        'no trust scoring',
      ],
    },
    {
      id: 'discover-url',
      command: 'discover',
      mode: 'discover --url',
      status: 'implemented',
      inputBoundary: 'explicit http or https URL',
      outputFiles: ['discovery-report.json', 'manifest.json'],
      summary:
        'bounded static website inspection for the explicit URL plus same-origin /llms.txt and /sitemap.xml, recording explicit observed HTTP freshness validators, descriptive manifest contract metadata, content-free input provenance summary metadata, content-free artifact summary metadata, and a compact content-free candidate evidence manifest index',
      limitations: [
        'candidate evidence for agent review only',
        'input provenance summaries are content-free candidate-evidence metadata only',
        'artifact summaries are content-free manifest metadata only',
        'candidate evidence index is manifest metadata only',
        'observed HTTP freshness evidence is not freshness validation or remote refresh',
        'no linked candidate fetching',
        'no JavaScript rendering',
        'no broad crawling',
        'no source selection',
      ],
    },
    {
      id: 'source-truth-inspect',
      command: 'source-truth inspect',
      mode: 'source-truth inspect --source',
      status: 'implemented',
      inputBoundary: 'explicit local file or directory',
      outputFiles: ['stdout JSON evidence report'],
      factFamilies: [
        'export facts',
        'optional direct-declaration AST signatures and member rosters',
        'package/config facts',
        'path/filename test/example context facts',
        'AST-observed test-case label context facts',
      ],
      summary: 'deterministic local evidence extraction for conservative observed facts',
      limitations: [
        'no behavior inference',
        'member rosters omit bodies and initializer values',
        'no assertion parsing',
        'no test body serialization',
        'test-case labels are not behavior or correctness proof',
        'no test execution',
        'no framework inference',
        'no route inference',
        'no re-export resolution',
        'local explicit sources only',
      ],
    },
    {
      id: 'source-truth-generate',
      command: 'source-truth generate',
      mode: 'source-truth generate --source --output-dir',
      status: 'implemented',
      inputBoundary: 'explicit local file or directory',
      outputFiles: ['source-truth-report.json', 'source-truth.md', 'manifest.json', 'failure.json'],
      factFamilies: [
        'export facts',
        'optional direct-declaration AST signatures and member rosters',
        'package/config facts',
        'path/filename test/example context facts',
        'AST-observed test-case label context facts',
      ],
      summary:
        'evidence-bound Markdown and provenance files from source-truth inspection, with descriptive manifest contract metadata, content-free input provenance summary metadata, content-free artifact summary metadata, and deterministic content-free source-file line/token metadata in the manifest',
      limitations: [
        'input provenance summaries are content-free manifest metadata only',
        'manifest source-file line/token metadata is content-free text metadata, not behavior verification',
        'artifact summaries are content-free manifest metadata only',
        'no behavior inference',
        'member rosters omit bodies and initializer values',
        'no assertion parsing',
        'no test body serialization',
        'test-case labels are not behavior or correctness proof',
        'no test execution',
        'no framework inference',
        'no route inference',
        'no re-export resolution',
        'local explicit sources only',
      ],
    },
    {
      id: 'source-truth-verify-docs',
      command: 'source-truth verify-docs',
      mode: 'source-truth verify-docs --source --docs --output-dir',
      status: 'implemented',
      inputBoundary:
        'explicit local source file or directory plus explicit local Markdown/MDX docs file or directory',
      options: ['--source <path>', '--docs <path>', '--output-dir <dir>'],
      outputFiles: ['source-verification-report.json', 'manifest.json', 'failure.json'],
      factFamilies: [
        'source export facts from source-truth inspection',
        'docs inline-code identifier references',
        'exact lexical exported-name matches',
        'unmatched docs references',
      ],
      summary:
        'deterministic local evidence comparing explicit docs references with observed source exported names and emitting descriptive manifest contract metadata, content-free input provenance summary metadata, content-free artifact summary metadata, plus compact content-free source/docs file evidence index metadata',
      limitations: [
        'explicit local paths only',
        'Markdown/MDX-style text docs only',
        'input provenance summaries are content-free manifest metadata only',
        'file evidence index metadata is content-free and derived only from the local report',
        'artifact summaries are content-free manifest metadata only',
        'docs evidence limited to inline-code identifiers and empty call identifiers',
        'exact matches are lexical exported-name evidence only',
        'unmatched references are observations, not failures',
        'no behavior inference',
        'no assertion parsing',
        'no test execution',
        'no framework inference',
        'no route inference',
        'no re-export resolution beyond existing source-truth facts',
        'no automatic source selection',
      ],
    },
    {
      id: 'agent-context',
      command: 'agent context',
      mode: 'agent context --json',
      status: 'implemented',
      inputBoundary: 'packaged context and skill files only',
      outputFiles: ['stdout JSON metadata'],
      summary: 'read-only metadata for packaged agent context and skill artifacts',
      limitations: [
        'packaged context and skill metadata only',
        'does not install/register skills',
        'no user config writes',
        'no environment probing',
        'no network',
      ],
    },
    {
      id: 'agent-doctor',
      command: 'agent doctor',
      mode: 'agent doctor --json',
      status: 'implemented',
      inputBoundary: 'packaged artifacts and explicit process environment PATH only',
      options: ['--json'],
      outputFiles: ['stdout diagnostics', 'stdout JSON diagnostics'],
      summary:
        'read-only diagnostics for packaged context/skill artifact readability, expected binary metadata, PATH visibility, and skipped host-install checks',
      limitations: [
        'does not install/register skills',
        'does not write user config',
        'does not mutate host skill directories',
        'does not perform network access',
        'PATH check is informational and may warn in development',
        'host skill installation check is skipped unless a future explicit option is implemented',
        'no source-selection or task-fit inference',
      ],
    },
    {
      id: 'parser-plugin-manifest-validate',
      command: 'plugins validate',
      mode: 'plugins validate --manifest',
      status: 'implemented',
      inputBoundary: 'explicit local JSON parser plugin manifest file',
      options: ['--manifest <path>', '--json'],
      outputFiles: ['stdout validation result', 'stdout JSON validation result'],
      summary:
        'deterministic read-only validation of parser plugin manifest metadata without loading plugin modules',
      limitations: [
        'manifest validation only',
        'does not load, import, or execute plugin modules',
        'does not enable custom parser execution',
        'does not generate custom parsers',
        'does not select plugin manifests or sources',
        'no network',
        'no file writes',
      ],
    },
    {
      id: 'generate-source',
      command: 'generate',
      mode: 'generate --source',
      status: 'implemented',
      inputBoundary: 'explicit local file or directory',
      options: [
        '--source <path>',
        '--format auto|markdown|mdx|openapi|openref|rst|html',
        '--parser-plugin-manifest <path> with explicit custom --format <plugin-format-id>; directory sources require directorySupport: true',
        '--chunks jsonl',
        '--preset swift-book',
      ],
      outputFiles: ['manifest.json', 'llm-docs/*-llms.txt', 'chunks/semantic-chunks.jsonl'],
      summary:
        'deterministic local source parsing through the registered parser or an explicit local parser plugin and universal formatter, with descriptive manifest contract metadata, content-free input provenance summary metadata, content-free artifact summary metadata, opt-in semantic chunk JSONL export for built-in source generation, compact chunk manifest indexes, and a scoped swift-book preset',
      limitations: [
        'local files and directories only',
        'input provenance summaries are content-free manifest metadata only',
        'artifact summaries are content-free manifest metadata only',
        'no URL fetching',
        'no discovery report consumption',
        'no candidate auto-selection',
        'parser plugin generation requires --source <local-file-or-directory>, --parser-plugin-manifest <path>, and a custom explicit --format id',
        'parser plugin directory generation requires directorySupport: true on the selected manifest format',
        'parser plugin code is trusted local code executed for generation and is not sandboxed',
        'no parser plugin discovery, installation, package resolution, or auto-selection',
        'swift-book preset requires explicit --source and adds deterministic output defaults only',
        'no source selection decision',
        'semantic chunk JSONL is emitted only when --chunks jsonl is requested',
        'semantic chunk manifest indexes are source-docs JSONL metadata only',
      ],
    },
    {
      id: 'parser-plugin-execution',
      command: 'generate',
      mode: 'generate --source <local-file-or-directory> --parser-plugin-manifest <path> --format <plugin-format-id>',
      status: 'implemented',
      inputBoundary:
        'one explicit local source file or directory, one explicit local parser plugin manifest, and one explicit custom plugin format id',
      options: [
        '--source <local-file-or-directory>',
        '--parser-plugin-manifest <path>',
        '--format <id>',
      ],
      outputFiles: ['manifest.json', 'llm-docs/*-llms.txt'],
      summary:
        'explicit parser plugin execution through one declared local module, normalized through the universal formatter with descriptive manifest contract metadata, content-free input provenance summary metadata, content-free artifact summary metadata, and parser plugin provenance in the source-docs manifest',
      limitations: [
        'explicit local source files or directories only',
        'input provenance summaries are content-free manifest metadata only',
        'artifact summaries are content-free manifest metadata only',
        'directory sources require directorySupport: true on the selected manifest format',
        'requires a custom plugin format id declared by the manifest',
        'rejects built-in formats and --format auto',
        'no --chunks support with parser plugins',
        'no --preset support with parser plugins',
        'no parser plugin discovery or auto-selection',
        'no plugin installation or package resolution',
        'plugin code is trusted local code and is not sandboxed',
        'verify checks recorded plugin manifest metadata and hashes without importing plugin code',
        'no network added by the CLI',
      ],
    },
    {
      id: 'generate-preset-swift-book',
      command: 'generate',
      mode: 'generate --source --preset swift-book',
      status: 'implemented',
      inputBoundary: 'explicit local Markdown or DocC-style source path',
      options: ['--source <path>', '--preset swift-book', '--format markdown', '--chunks jsonl'],
      outputFiles: [
        'manifest.json',
        'llm-docs/swift-book-full-llms.txt',
        'chunks/semantic-chunks.jsonl',
      ],
      summary:
        'deterministic Swift Programming Language output defaults over an explicit local source path',
      limitations: [
        'requires explicit --source',
        'local files and directories only',
        'Markdown parser only',
        'no TSPL.docc path inference',
        'no repo clone or cache',
        'preset generation itself does not refresh existing outputs',
        'no source-code verification',
        'no automatic source selection',
        'preset metadata does not select or verify source truth',
      ],
    },
    {
      id: 'generate-sdk',
      command: 'generate',
      mode: 'generate --sdk',
      status: 'implemented',
      inputBoundary: 'configured SDK manifest entry',
      options: ['--sdk <sdk>', '--sdk-version <version>', '--format openref|openref-0.1'],
      outputFiles: [
        'manifest.json',
        'parsed/<sdk>-<resolved-version>-spec.json',
        'llm-docs/*-llms.txt',
      ],
      summary:
        'configured OpenRef SDK generation through the existing compatibility flow with descriptive manifest contract metadata, content-free input provenance summary metadata, and content-free artifact summary metadata',
      limitations: [
        'configured SDKs only',
        'input provenance summaries are content-free manifest metadata only',
        'artifact summaries are content-free manifest metadata only',
        'no preset generation',
        'no discovery report consumption',
      ],
    },
    {
      id: 'verify-discovery-report',
      command: 'verify',
      mode: 'verify --manifest or verify --output-dir',
      status: 'implemented',
      inputBoundary: 'discovery-report manifest.json',
      summary:
        'file integrity, basic schema consistency, required V2 descriptive manifest contract validation, required V2 content-free input provenance summary validation, required V2 content-free artifact summary validation, required V2 content-free candidate evidence index checks, and optional refresh provenance validation for discovery report manifests',
      limitations: [
        'discovery-report manifest mode only',
        'candidate evidence for agent review only',
        'input provenance summaries are content-free and do not score or select candidates',
        'artifact summaries are content-free and do not score candidates',
        'candidate evidence indexes are content-free and do not score candidates',
        'no task fit decision',
        'no source selection',
        'verify itself does not refresh discovery reports',
        'verify does not refresh remote freshness evidence',
        'no source-code verification',
      ],
    },
    {
      id: 'verify-configured-sdk',
      command: 'verify',
      mode: 'verify --manifest or verify --output-dir',
      status: 'implemented',
      inputBoundary: 'configured-sdk manifest.json',
      outputFiles: ['stdout verification result'],
      summary:
        'recorded generator/sdk/parser/formatter metadata, required V2 descriptive manifest contract validation, required V2 content-free input provenance summary validation, required V2 content-free artifact summary validation, source file hash, byte-size, required content-free source line/token metadata, generated output hash, byte-size, required manifest-recorded output line/token verification, and optional refresh provenance validation for configured SDK manifests',
      limitations: [
        'configured-sdk manifest mode only',
        'only verifies existing source and generated output files recorded in the manifest',
        'input provenance summaries are content-free manifest metadata only',
        'artifact summaries are content-free manifest metadata only',
        'source line/token metadata is deterministic content-free text metadata only',
        'verify does not refresh configured SDK outputs',
        'no repo freshness check',
        'no source-code verification',
      ],
    },
    {
      id: 'verify-source-docs',
      command: 'verify',
      mode: 'verify --manifest or verify --output-dir',
      status: 'implemented',
      inputBoundary: 'local-source-docs manifest.json',
      outputFiles: ['stdout verification result'],
      summary:
        'recorded generator/parser/formatter metadata, required V2 descriptive manifest contract validation, required V2 content-free input provenance summary validation, required V2 content-free artifact summary validation, source path, source file hash, byte-size, line-count, estimated-token, generated output hash, byte-size, line-count, estimated-token, optional semantic chunk index verification, and optional refresh provenance validation for local source docs manifests',
      limitations: [
        'local-source-docs manifest mode only',
        'input provenance summaries are content-free manifest metadata only',
        'artifact summaries are content-free manifest metadata only',
        'verify does not refresh outputs',
        'no repo freshness check',
        'no source-code verification',
      ],
    },
    {
      id: 'verify-source-truth-docs',
      command: 'verify',
      mode: 'verify --manifest or verify --output-dir',
      status: 'implemented',
      inputBoundary: 'source-truth-local-docs manifest.json',
      outputFiles: ['stdout verification result'],
      summary:
        'deterministic integrity and schema consistency checks for source-truth docs manifests, including required V2 descriptive manifest contract validation, required V2 content-free input provenance summary validation, required V2 content-free artifact summary validation, required content-free source-file line/token metadata, and optional refresh provenance validation when present',
      limitations: [
        'source-truth-local-docs manifest mode only',
        'input provenance summaries are content-free manifest metadata only',
        'artifact summaries are content-free manifest metadata only',
        'source-file line/token metadata is content-free text metadata only',
        'local generated evidence docs only',
        'verify does not refresh outputs',
        'no repo freshness check',
        'no source-code verification',
        'no behavior inference',
      ],
    },
    {
      id: 'verify-source-verification',
      command: 'verify',
      mode: 'verify --manifest or verify --output-dir',
      status: 'implemented',
      inputBoundary: 'source-verification-local-evidence manifest.json',
      outputFiles: ['stdout verification result'],
      summary:
        'deterministic source-verification report integrity, provenance, report-path, manifest/report summary, report-body count, sourceInspection.source consistency, required V2 descriptive manifest contract validation, required V2 content-free input provenance summary validation, required V2 content-free artifact summary validation, required V2 content-free file evidence index checks, and optional refresh provenance validation',
      limitations: [
        'source-verification-local-evidence manifest mode only',
        'input provenance summaries are content-free manifest metadata only',
        'artifact summaries are content-free manifest metadata only',
        'file evidence indexes are source/docs file metadata only',
        'verify does not refresh outputs or sources',
        'no additional source/docs inspection',
        'no broad official-docs claim checking',
        'no source-code behavior validation',
        'no task-fit, source-truth, or source-selection decision',
        'no proof that docs statements are correct',
      ],
    },
    {
      id: 'refresh-source-docs',
      command: 'refresh',
      mode: 'refresh --manifest or refresh --output-dir for local-source-docs',
      status: 'implemented',
      inputBoundary:
        'existing built-in-parser local-source-docs manifest.json with recorded local source path',
      options: ['--manifest <path>', '--output-dir <dir>'],
      outputFiles: ['manifest.json', 'llm-docs/*-llms.txt', 'chunks/semantic-chunks.jsonl'],
      summary:
        'deterministic regeneration of built-in-parser local source docs from the manifest-recorded explicit local source path, preserving opt-in chunk JSONL and chunk index metadata when the prior manifest recorded that output, writing current content-free input provenance summary metadata and content-free artifact summary metadata, recording verified refresh provenance metadata, followed by manifest integrity verification of regenerated outputs',
      limitations: [
        'built-in-parser local-source-docs manifests only',
        'input provenance summaries are content-free manifest metadata only',
        'parser-plugin local-source-docs manifests are not refreshed; rerun explicit generate --source --parser-plugin-manifest --format',
        'uses only source.resolvedPath, source.formatHint, preset metadata, and prior chunk-output presence from the existing manifest',
        'no URLs',
        'no repo freshness check',
        'no crawling',
        'no source selection',
        'does not consume discovery reports',
        'no source-code verification',
        'no remote network work',
        'no source project script execution',
      ],
    },
    {
      id: 'refresh-source-truth-docs',
      command: 'refresh',
      mode: 'refresh --manifest or refresh --output-dir for source-truth-local-docs',
      status: 'implemented',
      inputBoundary:
        'existing source-truth-local-docs manifest.json with recorded local source path',
      options: ['--manifest <path>', '--output-dir <dir>'],
      outputFiles: ['source-truth-report.json', 'source-truth.md', 'manifest.json'],
      summary:
        'deterministic regeneration of source-truth docs and content-free source-file line/token manifest metadata plus content-free input provenance summary metadata and content-free artifact summary metadata from the manifest-recorded explicit local source path, recording verified refresh provenance metadata, followed by manifest integrity verification of regenerated outputs',
      limitations: [
        'source-truth-local-docs manifests only',
        'input provenance summaries are content-free manifest metadata only',
        'uses only source.resolvedPath from the existing manifest',
        'no URLs',
        'no repo freshness check',
        'no crawling',
        'no source selection',
        'does not consume discovery reports',
        'no source-code verification',
        'no remote network work',
        'no source project script execution',
        'no behavior inference',
      ],
    },
    {
      id: 'refresh-configured-sdk',
      command: 'refresh',
      mode: 'refresh --manifest or refresh --output-dir for configured-sdk',
      status: 'implemented',
      inputBoundary:
        'existing configured-sdk manifest.json with recorded absolute local source.resolvedSpecPath',
      options: ['--manifest <path>', '--output-dir <dir>'],
      outputFiles: [
        'manifest.json',
        'parsed/<sdk>-<resolved-version>-spec.json',
        'llm-docs/*-llms.txt',
      ],
      summary:
        'deterministic regeneration of configured OpenRef SDK docs and content-free source spec line/token manifest metadata plus content-free input provenance summary metadata and content-free artifact summary metadata from the manifest-recorded absolute local spec path, recording verified refresh provenance metadata, followed by manifest integrity verification of regenerated outputs',
      limitations: [
        'configured-sdk manifests only',
        'input provenance summaries are content-free manifest metadata only',
        'requires source.resolvedSpecPath to be an absolute local non-symlink file outside the output directory',
        'uses only the recorded local spec path, SDK metadata, parser/formatter metadata, and manifest-recorded filename prefix',
        'OpenRef parser and legacy LLM formatter only',
        'no registry lookup',
        'no URL fetching',
        'no repo freshness check',
        'no crawling',
        'no source selection',
        'does not consume discovery reports',
        'no candidate report consumption',
        'no candidate auto-selection',
        'no source-code verification',
        'no remote network work',
        'no source project script execution',
      ],
    },
    {
      id: 'refresh-source-discovery-report',
      command: 'refresh',
      mode: 'refresh --manifest or refresh --output-dir for discovery-report source',
      status: 'implemented',
      inputBoundary:
        'existing discovery-report manifest.json with discovery.kind source and a local-bounded report source.resolvedPath',
      options: ['--manifest <path>', '--output-dir <dir>'],
      outputFiles: ['discovery-report.json', 'manifest.json'],
      summary:
        'deterministic rerun of local source discovery from discovery-report.json report.source.resolvedPath into the same output directory, preserving prior traversal bounds, writing current content-free input provenance summary metadata and content-free artifact summary metadata, recording verified refresh provenance metadata, and followed by manifest integrity verification',
      limitations: [
        'source discovery-report manifests only',
        'input provenance summaries are content-free candidate-evidence metadata only',
        'uses only report.source.resolvedPath and traversal.maxDepth/maxEntries/maxFiles from the existing local report',
        'candidate evidence for agent review only',
        'no docs generation',
        'no source selection',
        'repo discovery-report refresh is not supported',
        'URL discovery-report refresh is not supported',
        'no remote freshness refresh',
        'no repo cache update',
        'no broad crawling',
        'no candidate report consumption',
        'no candidate auto-selection',
        'no source-code verification',
        'no network access',
      ],
    },
    {
      id: 'refresh-source-verification-local-evidence',
      command: 'refresh',
      mode: 'refresh --manifest or refresh --output-dir for source-verification-local-evidence',
      status: 'implemented',
      inputBoundary:
        'existing successful source-verification-local-evidence manifest.json with a local source-verification-report.json',
      options: ['--manifest <path>', '--output-dir <dir>'],
      outputFiles: ['source-verification-report.json', 'manifest.json', 'failure.json'],
      summary:
        'deterministic rerun of explicit local source/docs lexical evidence from source-verification-report.json recorded source/docs paths into the same output directory, preserving prior docs traversal bounds, writing current content-free input provenance summary metadata and content-free artifact summary metadata, recording verified refresh provenance metadata, and followed by manifest integrity verification on success',
      limitations: [
        'source-verification-local-evidence manifests only',
        'input provenance summaries are content-free manifest metadata only',
        'uses only report.source.resolvedPath, report.docs.resolvedPath, and docs.traversal maxDepth/maxEntries/maxFiles/maxFileBytes from the existing local report',
        'explicit local paths only',
        'Markdown/MDX-style text docs only',
        'exact matches are lexical exported-name evidence only',
        'no broad official-docs claim checking',
        'no source-code behavior validation',
        'no freshness validation',
        'no remote refresh',
        'no repo cache update',
        'no crawling',
        'no source selection',
        'no candidate report consumption',
        'no candidate auto-selection',
        'no source-truth decision or proof that docs statements are correct',
        'no network access',
      ],
    },
    {
      id: 'list-sdks',
      command: 'list-sdks',
      mode: 'list-sdks',
      status: 'implemented',
      inputBoundary: 'configured SDK directory',
      outputFiles: ['stdout SDK list'],
      summary: 'list configured SDKs and versions',
      limitations: ['no source discovery', 'no generation'],
    },
    {
      id: 'validate-sdk',
      command: 'validate',
      mode: 'validate --sdk',
      status: 'implemented',
      inputBoundary: 'configured SDK manifest entry',
      outputFiles: ['stdout validation result'],
      summary: 'fetch and parse a configured SDK OpenRef spec',
      limitations: ['configured SDKs only', 'no docs generation'],
    },
  ],
  sourceTruth: {
    status: 'implemented-conservative-local-evidence',
    supportedFactFamilies: [
      'export facts',
      'optional direct-declaration AST signatures and member rosters',
      'package/config facts',
      'path/filename test/example context facts',
      'AST-observed test-case label context facts',
    ],
    limitations: [
      'no behavior inference',
      'member rosters omit bodies and initializer values',
      'no assertion parsing',
      'no test body serialization',
      'test-case labels are not behavior or correctness proof',
      'no test execution',
      'no framework inference',
      'no route inference',
      'no re-export resolution',
      'local explicit sources only',
    ],
  },
  plannedUnsupported: [
    {
      id: 'generate-preset-additional',
      command: 'generate --preset <name> except swift-book',
      status: 'planned-unsupported',
      reason:
        'only --preset swift-book over an explicit local --source path is implemented; additional presets remain planned',
    },
    {
      id: 'refresh-unsupported-manifests',
      command:
        'refresh for parser-plugin source-docs, repo/URL discovery reports, URL, repo, website, freshness, broad verification, or source-code workflows',
      status: 'planned-unsupported',
      reason:
        'only explicit built-in-parser local-source-docs, source-truth-local-docs, configured-sdk manifests with recorded absolute local spec paths, local source discovery-report manifests, and source-verification-local-evidence manifests can be refreshed; parser-plugin source-docs, repo/URL discovery-report refresh, remote freshness refresh, broad crawling, broad official-docs behavior/API verification refresh, and source-code verification refresh remain planned',
    },
    {
      id: 'source-code-verification',
      command: 'broad source verification for official docs',
      status: 'planned-unsupported',
      reason:
        'broad official-docs behavior/API claim verification remains planned; implemented source-truth verify-docs is explicit-local lexical evidence only',
    },
    {
      id: 'broad-crawling',
      command: 'broad website crawling',
      status: 'planned-unsupported',
      reason:
        'website discovery is bounded to explicit URL plus fixed same-origin well-known resources',
    },
    {
      id: 'automatic-source-selection',
      command: 'automatic source selection',
      status: 'planned-unsupported',
      reason: 'agents review candidate evidence and explicitly choose sources',
    },
    {
      id: 'framework-route-understanding',
      command: 'framework or route understanding',
      status: 'planned-unsupported',
      reason: 'source-truth inspection does not infer framework identity or routes',
    },
    {
      id: 'behavior-level-code-docs',
      command: 'behavior-level generation from source code',
      status: 'planned-unsupported',
      reason:
        'source-truth generation is limited to observed export, signature, member-roster, package/config, and path context facts',
    },
    {
      id: 'parser-plugin-broader-workflows',
      command:
        'parser plugin discovery, install, package resolution, auto-detection, sandboxing, and broad custom parser workflows',
      status: 'planned-unsupported',
      reason:
        'only explicit local parser plugin generation is implemented for one source file or a directory whose selected manifest format declares directorySupport: true; discovery, install, package resolution, auto-selection, sandboxing, and broad custom parser workflows remain planned/unsupported',
    },
    {
      id: 'agent-install-codex',
      command: 'agent install codex',
      status: 'planned-unsupported',
      reason:
        'no current CLI skill installer; installing/registering skills remains separate from packaged context metadata',
    },
  ],
} as const;
