import { lstat, readFile, realpath } from 'node:fs/promises';
import { basename, dirname, isAbsolute, join, parse, relative, resolve, sep } from 'node:path';

import { isUrlLikeInput } from './discovery.js';
import {
  DISCOVERY_REPORT_MODE,
  CONFIGURED_SDK_MODE,
  MANIFEST_SCHEMA_VERSION,
  validateSourceDocsPresetContract,
  verifyGenerationManifest,
  type VerifyGenerationManifestResult,
} from './manifest.js';
import {
  generateSourceDocs,
  SOURCE_DOCS_MODE,
  type SourceDocsGeneratorMetadata,
  type SourceDocsPresetMetadata,
} from './source-docs.js';
import { generateSourceTruthDocs, SOURCE_TRUTH_DOCS_MODE } from './source-truth-docs.js';

const SOURCE_DOCS_FORMAT_HINTS = new Set([
  'auto',
  'markdown',
  'mdx',
  'openapi',
  'openref',
  'rst',
  'html',
]);
const SOURCE_DOCS_CHUNKS_JSONL_KIND = 'semantic-chunks-jsonl';

export class RefreshManifestError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'RefreshManifestError';
  }
}

export class RefreshManifestVerificationError extends RefreshManifestError {
  checkedFiles: number;
  failures: string[];

  constructor(result: VerifyGenerationManifestResult) {
    super(
      `post-refresh manifest verification failed with ${result.failures.length} failure(s)`
    );
    this.name = 'RefreshManifestVerificationError';
    this.checkedFiles = result.checkedFiles;
    this.failures = result.failures;
  }
}

export interface RefreshManifestOptions {
  manifestPath: string;
  generator: SourceDocsGeneratorMetadata;
}

export interface RefreshManifestResult {
  mode: typeof SOURCE_DOCS_MODE | typeof SOURCE_TRUTH_DOCS_MODE;
  manifestPath: string;
  outputDir: string;
  sourcePath: string;
  sourceFiles: number;
  generatedOutputs: number;
  postRefreshVerification: {
    status: 'passed';
    checkedFiles: number;
  };
  chunkOutputPath?: string;
  presetName?: string;
}

export async function refreshGenerationManifest(
  options: RefreshManifestOptions
): Promise<RefreshManifestResult> {
  const manifestPath = resolve(options.manifestPath);
  const manifest = await readRefreshManifest(manifestPath);

  if (manifest.mode === SOURCE_DOCS_MODE) {
    return refreshSourceDocsManifest({
      manifestPath,
      manifest,
      generator: options.generator,
    });
  }

  if (manifest.mode === SOURCE_TRUTH_DOCS_MODE) {
    return refreshSourceTruthDocsManifest({ manifestPath, manifest });
  }

  if (manifest.mode === CONFIGURED_SDK_MODE) {
    throw new RefreshManifestError(
      'refresh does not support configured-sdk manifests; only local-source-docs and source-truth-local-docs manifests with recorded local source paths are supported'
    );
  }

  if (manifest.mode === DISCOVERY_REPORT_MODE) {
    throw new RefreshManifestError(
      'refresh does not support discovery-report manifests; discovery reports are candidate evidence and are not regenerated by refresh'
    );
  }

  throw new RefreshManifestError(
    `unsupported refresh manifest mode: ${String(
      manifest.mode
    )}; supported modes are local-source-docs and source-truth-local-docs`
  );
}

async function readRefreshManifest(manifestPath: string): Promise<Record<string, unknown>> {
  let manifest: unknown;

  try {
    manifest = JSON.parse(await readFile(manifestPath, 'utf-8')) as unknown;
  } catch (error) {
    if (isFileNotFoundError(error)) {
      throw new RefreshManifestError(`manifest not found: ${manifestPath}`);
    }

    throw new RefreshManifestError(`malformed manifest JSON: ${errorMessage(error)}`);
  }

  if (!isObjectRecord(manifest)) {
    throw new RefreshManifestError('malformed manifest: root must be an object');
  }

  if (manifest.schemaVersion !== MANIFEST_SCHEMA_VERSION) {
    throw new RefreshManifestError(
      `unsupported manifest schemaVersion: ${String(manifest.schemaVersion)}`
    );
  }

  return manifest;
}

async function refreshSourceDocsManifest(options: {
  manifestPath: string;
  manifest: Record<string, unknown>;
  generator: SourceDocsGeneratorMetadata;
}): Promise<RefreshManifestResult> {
  const source = requiredObject(options.manifest.source, 'source');
  const generatedOutputs = requiredArray(options.manifest.generatedOutputs, 'generatedOutputs');
  const sourcePath = requiredAbsoluteLocalPath(source.resolvedPath, 'source.resolvedPath');
  const formatHint = requiredNonEmptyString(source.formatHint, 'source.formatHint');

  if (!SOURCE_DOCS_FORMAT_HINTS.has(formatHint)) {
    throw new RefreshManifestError(
      `malformed manifest: source.formatHint must be a supported source format hint`
    );
  }

  const preset = sourceDocsPresetFromManifest(options.manifest.preset);
  const outputDir = dirname(options.manifestPath);
  await assertExistingLocalSourcePath(sourcePath);
  await assertSourceOutsideRefreshOutput({ sourcePath, outputDir });
  const chunks = generatedOutputs.some(
    (output) => isObjectRecord(output) && output.kind === SOURCE_DOCS_CHUNKS_JSONL_KIND
  )
    ? 'jsonl'
    : undefined;

  const result = await generateSourceDocs({
    source: sourcePath,
    outputDir,
    format: formatHint,
    ...(chunks === undefined ? {} : { chunks }),
    ...(preset === undefined
      ? {}
      : {
          preset,
          output: {
            filenamePrefix: preset.defaults.filenamePrefix,
            title: preset.defaults.title,
            systemPrompt: preset.defaults.systemPrompt,
          },
        }),
    generator: options.generator,
  });
  const chunkOutput = result.manifest.generatedOutputs.find(
    (output) => output.kind === SOURCE_DOCS_CHUNKS_JSONL_KIND
  );

  return withPostRefreshVerification({
    mode: SOURCE_DOCS_MODE,
    manifestPath: result.manifestPath,
    outputDir: result.outputDir,
    sourcePath: result.manifest.source.resolvedPath,
    sourceFiles: result.manifest.sourceFiles.length,
    generatedOutputs: result.manifest.generatedOutputs.length,
    ...(chunkOutput === undefined ? {} : { chunkOutputPath: chunkOutput.path }),
    ...(result.manifest.preset === undefined ? {} : { presetName: result.manifest.preset.name }),
  });
}

async function refreshSourceTruthDocsManifest(options: {
  manifestPath: string;
  manifest: Record<string, unknown>;
}): Promise<RefreshManifestResult> {
  const source = requiredObject(options.manifest.source, 'source');
  requiredArray(options.manifest.generatedOutputs, 'generatedOutputs');
  const sourcePath = requiredAbsoluteLocalPath(source.resolvedPath, 'source.resolvedPath');
  const outputDir = dirname(options.manifestPath);
  await assertExistingLocalSourcePath(sourcePath);
  await assertSourceOutsideRefreshOutput({ sourcePath, outputDir });
  const result = await generateSourceTruthDocs({
    source: sourcePath,
    outputDir,
  });

  return withPostRefreshVerification({
    mode: SOURCE_TRUTH_DOCS_MODE,
    manifestPath: result.manifestPath,
    outputDir: result.outputDir,
    sourcePath: result.manifest.source.resolvedPath,
    sourceFiles: result.manifest.sourceFiles.length,
    generatedOutputs: result.manifest.generatedOutputs.length,
  });
}

async function withPostRefreshVerification(
  result: Omit<RefreshManifestResult, 'postRefreshVerification'>
): Promise<RefreshManifestResult> {
  const verification = await verifyGenerationManifest({ manifestPath: result.manifestPath });

  if (verification.failures.length > 0) {
    throw new RefreshManifestVerificationError(verification);
  }

  return {
    ...result,
    postRefreshVerification: {
      status: 'passed',
      checkedFiles: verification.checkedFiles,
    },
  };
}

function sourceDocsPresetFromManifest(preset: unknown): SourceDocsPresetMetadata | undefined {
  if (preset === undefined) {
    return undefined;
  }

  const failures = validateSourceDocsPresetContract(preset);

  if (failures.length > 0) {
    throw new RefreshManifestError(
      `malformed manifest: ${failures.join('; ')}`
    );
  }

  return preset as SourceDocsPresetMetadata;
}

function requiredObject(value: unknown, label: string): Record<string, unknown> {
  if (!isObjectRecord(value)) {
    throw new RefreshManifestError(`malformed manifest: missing ${label} object`);
  }

  return value;
}

function requiredArray(value: unknown, label: string): unknown[] {
  if (!Array.isArray(value)) {
    throw new RefreshManifestError(`malformed manifest: missing ${label} array`);
  }

  return value;
}

function requiredNonEmptyString(value: unknown, label: string): string {
  if (typeof value !== 'string' || value.length === 0) {
    throw new RefreshManifestError(`malformed manifest: ${label} must be a non-empty string`);
  }

  return value;
}

function requiredAbsoluteLocalPath(value: unknown, label: string): string {
  const path = requiredNonEmptyString(value, label);

  if (isUrlLikeInput(path)) {
    throw new RefreshManifestError(`malformed manifest: ${label} must be a local path`);
  }

  if (!isAbsolute(path)) {
    throw new RefreshManifestError(`malformed manifest: ${label} must be absolute`);
  }

  return path;
}

async function assertExistingLocalSourcePath(sourcePath: string): Promise<void> {
  try {
    const stats = await lstat(sourcePath);

    if (stats.isSymbolicLink()) {
      throw new RefreshManifestError(
        `manifest source path must not be a symbolic link: ${sourcePath}`
      );
    }

    if (!stats.isFile() && !stats.isDirectory()) {
      throw new RefreshManifestError(
        `manifest source path must be a local file or directory: ${sourcePath}`
      );
    }

    await assertNoSymlinkPathComponents(sourcePath);
  } catch (error) {
    if (error instanceof RefreshManifestError) {
      throw error;
    }

    if (isFileNotFoundError(error)) {
      throw new RefreshManifestError(`manifest source path not found: ${sourcePath}`);
    }

    throw new RefreshManifestError(
      `manifest source path cannot be read: ${sourcePath}: ${errorMessage(error)}`
    );
  }
}

async function assertNoSymlinkPathComponents(sourcePath: string): Promise<void> {
  const parsedPath = parse(sourcePath);
  const parts = sourcePath.slice(parsedPath.root.length).split(sep).filter(Boolean);
  let currentPath = parsedPath.root;

  for (const part of parts) {
    currentPath = join(currentPath, part);

    const stats = await lstat(currentPath);

    if (stats.isSymbolicLink()) {
      throw new RefreshManifestError(
        `manifest source path must not contain a symbolic link component: ${currentPath}`
      );
    }
  }
}

async function assertSourceOutsideRefreshOutput(options: {
  sourcePath: string;
  outputDir: string;
}): Promise<void> {
  const resolvedOutputDir = resolve(options.outputDir);
  const effectiveOutputPath = await resolveEffectiveOutputPath(resolvedOutputDir);
  const canonicalSourcePath = await realpathIfExists(options.sourcePath);

  if (
    (canonicalSourcePath !== undefined &&
      isSameOrDescendant(effectiveOutputPath, canonicalSourcePath)) ||
    isSameOrDescendant(resolvedOutputDir, options.sourcePath)
  ) {
    throw new RefreshManifestError(
      'manifest source path must not be the same as, or inside, the manifest output directory'
    );
  }
}

async function realpathIfExists(path: string): Promise<string | undefined> {
  try {
    return await realpath(path);
  } catch {
    return undefined;
  }
}

async function resolveEffectiveOutputPath(outputDir: string): Promise<string> {
  const resolvedOutputDir = resolve(outputDir);
  const missingSegments: string[] = [];
  let currentPath = resolvedOutputDir;

  while (true) {
    try {
      const canonicalExistingPath = await realpath(currentPath);

      return missingSegments.length === 0
        ? canonicalExistingPath
        : join(canonicalExistingPath, ...missingSegments.reverse());
    } catch (error) {
      if (!isFileNotFoundError(error)) {
        throw error;
      }
    }

    const parentPath = dirname(currentPath);

    if (parentPath === currentPath) {
      return resolvedOutputDir;
    }

    missingSegments.push(basename(currentPath));
    currentPath = parentPath;
  }
}

function isSameOrDescendant(parentPath: string, candidatePath: string): boolean {
  const relativePath = relative(parentPath, candidatePath);

  return (
    relativePath === '' ||
    (relativePath !== '..' && !relativePath.startsWith(`..${sep}`) && !isAbsolute(relativePath))
  );
}

function isObjectRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isFileNotFoundError(error: unknown): boolean {
  return (
    error instanceof Error && 'code' in error && (error as NodeJS.ErrnoException).code === 'ENOENT'
  );
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
