/**
 * Verifier and validators for source-docs manifests.
 */

import { lstat, open } from 'node:fs/promises';
import { dirname, isAbsolute, resolve, win32 } from 'node:path';

import {
  errorMessage,
  isFileNotFoundError,
  isNonEmptyString,
  isNonNegativeInteger,
  isObjectRecord,
} from '../../../utils/guards.js';
import { isSha256Hash, isUnprefixedSha256Hash } from '../../../utils/hash.js';
import { isSanitizedFilenameSegment } from '../../../utils/filename-prefix.js';
import { compareStringsByCodeUnit } from '../../../utils/sort.js';
import { aggregateSourceFilesHash } from '../../../utils/source-files-hash.js';
import { scanSourceDocsDirectorySelection } from '../../source-docs.js';
import {
  buildSemanticChunkJsonlManifestIndex,
  hashSemanticChunkManifestIndex,
  semanticChunkManifestIndexesEqual,
  type SemanticChunkManifestIndex,
  type SemanticChunkManifestIndexChunk,
} from '../../semantic-chunk-index.js';
import {
  validateParserPluginManifestFile,
  type ParserPluginFormatMetadata,
  type ParserPluginManifestMetadata,
} from '../../parser-plugin-manifest.js';
import {
  SOURCE_DOCS_FORMATTER_FORMAT,
  SOURCE_DOCS_FORMATTER_NAME,
  SOURCE_DOCS_FORMAT_HINTS,
  SOURCE_DOCS_GENERATED_OUTPUT_KINDS,
  SOURCE_DOCS_MODE,
  SOURCE_DOCS_PLUGIN_FORMAT_ID_PATTERN,
  SOURCE_DOCS_RESOLVED_FORMATS,
  SOURCE_DOCS_SEMANTIC_CHUNK_INDEX_CHUNK_KEYS,
  SOURCE_DOCS_SEMANTIC_CHUNK_INDEX_KEYS,
  SOURCE_DOCS_SEMANTIC_CHUNK_JSONL_KIND,
  SOURCE_DOCS_SOURCE_TYPES,
  SOURCE_DOCS_SWIFT_BOOK_PRESET_LIMITATIONS,
  SOURCE_DOCS_SWIFT_BOOK_PRESET_METADATA,
  SOURCE_DOCS_SWIFT_BOOK_PRESET_NAME,
} from '../constants.js';
import {
  formatAllowedOutputKinds,
  isInsideDirectory,
  isPositiveInteger,
  isSourceDocsSourceType,
  isStringArray,
} from '../predicates.js';
import {
  optionalStringArraysEqual,
  stringArraysEqual,
  validateAllowedKeys,
  validateOptionalStringArray,
} from '../field-validators.js';
import {
  describeFile,
  hasEmptyOrParentPathSegment,
  isUrlLikePath,
  verifyFile,
  verifyPathType,
} from '../fs-verify.js';
import type { FileCheck, PathTypeCheck } from '../fs-verify.js';
import type { VerifyGenerationManifestResult, VerifyTierResult } from '../types.js';
import { validateRequiredManifestContract } from '../contract.js';
import { validateRequiredInputProvenance } from '../provenance.js';
import { validateRequiredArtifactSummary } from '../artifact-summary.js';
import { validateRefreshProvenance } from '../refresh-provenance.js';
import { validateGeneratedOutputs, validateGeneratorMetadata } from './shared.js';

export async function verifySourceDocsManifest(
  manifestPath: string,
  manifest: Record<string, unknown>
): Promise<VerifyGenerationManifestResult> {
  const failures: string[] = [];
  const manifestDir = dirname(manifestPath);
  const generator = manifest.generator;
  const source = manifest.source;
  const sourceFiles = manifest.sourceFiles;
  const parser = manifest.parser;
  const formatter = manifest.formatter;
  const generatedOutputs = manifest.generatedOutputs;
  const semanticChunkIndexes = manifest.semanticChunkIndexes;
  const preset = manifest.preset;

  if (!isObjectRecord(generator)) {
    failures.push('malformed manifest: missing generator object');
  } else {
    validateGeneratorMetadata(generator, failures);
  }

  if (!isObjectRecord(source)) {
    failures.push('malformed manifest: missing source object');
  }

  if (!Array.isArray(sourceFiles)) {
    failures.push('malformed manifest: missing sourceFiles array');
  }

  if (!isObjectRecord(parser)) {
    failures.push('malformed manifest: missing parser object');
  }

  if (!isObjectRecord(formatter)) {
    failures.push('malformed manifest: missing formatter object');
  }

  if (!Array.isArray(generatedOutputs)) {
    failures.push('malformed manifest: missing generatedOutputs array');
  }

  const hasParserPluginMetadata =
    isObjectRecord(parser) && (parser as Record<string, unknown>).plugin !== undefined;

  if (manifest.refresh !== undefined) {
    if (hasParserPluginMetadata) {
      failures.push(
        'malformed manifest: refresh is supported for local-source-docs manifests only when generated by the built-in parser'
      );
    } else {
      validateRefreshProvenance(manifest.refresh, SOURCE_DOCS_MODE, failures);
    }
  }

  if (failures.length > 0) {
    return {
      manifestPath,
      checkedFiles: 0,
      failures,
    };
  }

  // Two integrity tiers checked separately: `outputChecks` are the
  // self-contained generated pack (always verified), `sourceChecks` are the
  // external recorded source (verified only when the source is available).
  const outputChecks: FileCheck[] = [];
  const sourceChecks: FileCheck[] = [];
  const pathTypeChecks: PathTypeCheck[] = [];
  const sourceRecord = source as Record<string, unknown>;
  const sourceFileRecords = sourceFiles as unknown[];
  const parserRecord = parser as Record<string, unknown>;
  const formatterRecord = formatter as Record<string, unknown>;
  const outputRecords = generatedOutputs as unknown[];
  const sourceInput = sourceRecord.input;
  const sourcePath = sourceRecord.resolvedPath;
  const sourceType = sourceRecord.type;
  const sourceFormatHint = sourceRecord.formatHint;
  const sourceResolvedFormat = sourceRecord.resolvedFormat;
  const sourceByteSize = sourceRecord.byteSize;
  const sourceHash = sourceRecord.hash;
  const sourceFileCount = sourceRecord.fileCount;
  const sourceAggregateHash = sourceRecord.aggregateHash;
  const parserPluginMetadata = validateSourceDocsParserPluginMetadata(
    parserRecord.plugin,
    failures,
    sourceChecks
  );
  const parserPluginFormatId = parserPluginMetadata?.format.id;

  if (!isNonEmptyString(sourceInput)) {
    failures.push('malformed manifest: source.input must be a non-empty string');
  }

  if (!isNonEmptyString(sourceType) || !SOURCE_DOCS_SOURCE_TYPES.has(sourceType)) {
    failures.push('malformed manifest: source.type must be file or directory');
  }

  if (hasParserPluginMetadata && preset !== undefined) {
    failures.push('malformed manifest: parser.plugin source manifests must not include preset');
  }

  if (hasParserPluginMetadata && semanticChunkIndexes !== undefined) {
    failures.push(
      'malformed manifest: parser.plugin source manifests must not include semanticChunkIndexes'
    );
  }

  if (!isNonEmptyString(sourceFormatHint)) {
    failures.push('malformed manifest: source.formatHint must be a supported source format hint');
  } else if (hasParserPluginMetadata) {
    if (parserPluginFormatId !== undefined && sourceFormatHint !== parserPluginFormatId) {
      failures.push('malformed manifest: source.formatHint must match parser.plugin.format.id');
    }
  } else if (!SOURCE_DOCS_FORMAT_HINTS.has(sourceFormatHint)) {
    failures.push('malformed manifest: source.formatHint must be a supported source format hint');
  }

  if (!isNonEmptyString(sourceResolvedFormat)) {
    failures.push('malformed manifest: source.resolvedFormat must be a supported source format');
  } else if (hasParserPluginMetadata) {
    if (parserPluginFormatId !== undefined && sourceResolvedFormat !== parserPluginFormatId) {
      failures.push('malformed manifest: source.resolvedFormat must match parser.plugin.format.id');
    }
  } else if (!SOURCE_DOCS_RESOLVED_FORMATS.has(sourceResolvedFormat)) {
    failures.push('malformed manifest: source.resolvedFormat must be a supported source format');
  }

  validateSourceDocsParserMetadata(
    parserRecord,
    sourceResolvedFormat,
    parserPluginFormatId,
    failures
  );
  validateSourceDocsFormatterMetadata(formatterRecord, failures);

  if (!isNonEmptyString(sourcePath)) {
    failures.push('malformed manifest: source.resolvedPath must be a non-empty string');
  } else if (!isAbsolute(sourcePath)) {
    failures.push('malformed manifest: source.resolvedPath must be absolute');
  }

  if (sourceType === 'file') {
    if (!isNonNegativeInteger(sourceByteSize)) {
      failures.push('malformed manifest: source.byteSize must be a non-negative integer');
    }

    if (!isSha256Hash(sourceHash)) {
      failures.push('malformed manifest: source.hash must be a sha256 hash');
    }
  }

  if (sourceType === 'directory') {
    if (!isNonNegativeInteger(sourceFileCount)) {
      failures.push('malformed manifest: source.fileCount must be a non-negative integer');
    }

    if (!isSha256Hash(sourceAggregateHash)) {
      failures.push('malformed manifest: source.aggregateHash must be a sha256 hash');
    }
  }

  // Backward compatible: manifests generated before exclude-glob recording omit
  // source.excludeGlobs entirely; when absent the source-tier added-file rescan
  // is skipped with a note instead of failing.
  if (sourceRecord.excludeGlobs !== undefined) {
    if (
      !Array.isArray(sourceRecord.excludeGlobs) ||
      !sourceRecord.excludeGlobs.every((glob) => isNonEmptyString(glob))
    ) {
      failures.push(
        'malformed manifest: source.excludeGlobs must be an array of non-empty strings when present'
      );
    } else if (sourceType !== 'directory') {
      failures.push(
        'malformed manifest: source.excludeGlobs is recorded for directory sources only'
      );
    }
  }

  if (
    isNonEmptyString(sourcePath) &&
    isAbsolute(sourcePath) &&
    isSourceDocsSourceType(sourceType)
  ) {
    pathTypeChecks.push({
      label: 'source',
      path: sourcePath,
      expectedType: sourceType,
    });
  }

  const sourceFileEntries = validateSourceFiles({
    sourceFiles: sourceFileRecords,
    sourcePath,
    sourceType,
    sourceResolvedFormat,
    failures,
    fileChecks: sourceChecks,
  });

  if (sourceType === 'file' && sourceFileEntries.length !== 1) {
    failures.push(
      'malformed manifest: file source manifests must contain exactly one sourceFiles entry'
    );
  }

  if (
    sourceType === 'file' &&
    sourceFileEntries.length === 1 &&
    isNonNegativeInteger(sourceByteSize) &&
    isSha256Hash(sourceHash)
  ) {
    const sourceFile = sourceFileEntries[0];

    if (sourceFile !== undefined && sourceFile.byteSize !== sourceByteSize) {
      failures.push('malformed manifest: source.byteSize must match sourceFiles[0].byteSize');
    }

    if (sourceFile !== undefined && sourceFile.hash !== sourceHash) {
      failures.push('malformed manifest: source.hash must match sourceFiles[0].hash');
    }
  }

  if (
    sourceType === 'directory' &&
    isNonNegativeInteger(sourceFileCount) &&
    sourceFileCount !== sourceFileEntries.length
  ) {
    failures.push('malformed manifest: source.fileCount must match sourceFiles length');
  }

  if (
    sourceType === 'directory' &&
    isSha256Hash(sourceAggregateHash) &&
    sourceFileEntries.length === sourceFileRecords.length
  ) {
    const actualAggregateHash = aggregateSourceFilesHash(sourceFileEntries);

    if (sourceAggregateHash !== actualAggregateHash) {
      failures.push('malformed manifest: source.aggregateHash must match sourceFiles metadata');
    }
  }

  if (
    hasParserPluginMetadata &&
    sourceType === 'directory' &&
    parserPluginMetadata !== undefined &&
    parserPluginMetadata.format.directorySupport !== true
  ) {
    failures.push(
      'malformed manifest: parser.plugin directory source manifests require parser.plugin.format.directorySupport true'
    );
  }

  validateGeneratedOutputs({
    generatedOutputs: outputRecords,
    manifestDir,
    failures,
    fileChecks: outputChecks,
    requireTextMetadata: true,
    rejectSymlinks: true,
    allowedKinds: SOURCE_DOCS_GENERATED_OUTPUT_KINDS,
  });
  if (hasParserPluginMetadata) {
    validateSourceDocsParserPluginGeneratedOutputs(outputRecords, failures);
  }
  const semanticChunkIndexEntries = validateSourceDocsSemanticChunkIndexes({
    semanticChunkIndexes,
    generatedOutputs: outputRecords,
    manifestDir,
    failures,
  });
  validateSourceDocsPresetMetadata(preset, failures);
  validateSourceDocsOutputMetadata(manifest.output, failures);
  crossCheckGeneratedOutputFilenamePrefix(manifest.output, outputRecords, failures);

  validateRequiredManifestContract(manifest.manifestContract, SOURCE_DOCS_MODE, failures);
  validateRequiredInputProvenance(manifest.inputProvenance, SOURCE_DOCS_MODE, manifest, failures);
  validateRequiredArtifactSummary(manifest.artifactSummary, SOURCE_DOCS_MODE, manifest, failures);

  // A malformed manifest cannot be integrity-checked: structural failures block
  // every filesystem check and no tier is reported.
  if (failures.length > 0) {
    return {
      manifestPath,
      checkedFiles: 0,
      failures,
    };
  }

  // Outputs tier: ALWAYS hash-check the self-contained generated pack, even when
  // the recorded external source is missing (a relocated pack), so a verifier
  // can attest the outputs it holds.
  const outputFailures: string[] = [];
  for (const check of outputChecks) {
    await verifyFile(check, outputFailures);
  }
  await verifySourceDocsSemanticChunkIndexes({
    manifestDir,
    semanticChunkIndexes: semanticChunkIndexEntries,
    failures: outputFailures,
  });

  // Provenance cross-check: the manifest's self-reported source.git commit and
  // source.label are otherwise unbound, but the same values are stamped into the
  // primary generated output's <SYSTEM> header, which IS hash-bound by that
  // output's recorded hash. A mismatch is an outputs-tier failure (so it is
  // caught even under --outputs-only). Recorded here as it binds to the output.
  const notes: string[] = [];
  await crossCheckManifestProvenanceAgainstOutputHeader({
    manifestDir,
    source: sourceRecord,
    generatedOutputs: outputRecords,
    outputsClean: outputFailures.length === 0,
    failures: outputFailures,
    notes,
  });

  // Source tier: the external recorded source. A missing source root is reported
  // as `unavailable` (expected for a relocated pack) instead of a wall of
  // missing-file failures.
  const sourceFailures: string[] = [];
  let sourceCheckedFiles = 0;
  let sourceStatus: VerifyTierResult['status'];
  const sourceAvailable =
    isNonEmptyString(sourcePath) && isAbsolute(sourcePath)
      ? await pathExists(sourcePath)
      : false;

  if (!sourceAvailable) {
    sourceStatus = 'unavailable';
    sourceFailures.push(
      `source: recorded source path is unavailable at ${
        isNonEmptyString(sourcePath) ? sourcePath : '(unknown)'
      }`
    );
  } else {
    if (parserPluginMetadata !== undefined) {
      await verifySourceDocsParserPluginManifestMetadata(parserPluginMetadata, sourceFailures);
    }

    for (const check of pathTypeChecks) {
      await verifyPathType(check, sourceFailures);
    }

    for (const check of sourceChecks) {
      await verifyFile(check, sourceFailures);
    }

    // Added-file rescan: manifest-listed sourceFiles only prove the recorded
    // files are intact; a file added to the source directory would otherwise
    // pass silently. Re-walk the directory with the recorded traversal inputs
    // and fail on files generation would include today but the manifest lacks.
    if (
      !hasParserPluginMetadata &&
      sourceType === 'directory' &&
      isNonEmptyString(sourcePath) &&
      isNonEmptyString(sourceResolvedFormat)
    ) {
      await rescanSourceDirectoryForAddedFiles({
        sourcePath,
        resolvedFormat: sourceResolvedFormat,
        excludeGlobs: sourceRecord.excludeGlobs,
        recordedPaths: sourceFileEntries.map((entry) => entry.path),
        failures: sourceFailures,
        notes,
      });
    }

    sourceCheckedFiles = sourceChecks.length;
    sourceStatus = sourceFailures.length === 0 ? 'passed' : 'failed';
  }

  const outputs: VerifyTierResult = {
    status: outputFailures.length === 0 ? 'passed' : 'failed',
    checkedFiles: outputChecks.length,
    failures: outputFailures,
  };
  const sourceTier: VerifyTierResult = {
    status: sourceStatus,
    checkedFiles: sourceCheckedFiles,
    failures: sourceFailures,
  };

  return {
    manifestPath,
    checkedFiles: outputs.checkedFiles + sourceTier.checkedFiles,
    failures: [...outputFailures, ...sourceFailures],
    outputs,
    source: sourceTier,
    ...(notes.length > 0 ? { notes } : {}),
  };
}

function validateSourceDocsOutputMetadata(output: unknown, failures: string[]): void {
  // Backward compatible: v1 and pre-`output` manifests omit this block entirely.
  if (output === undefined) {
    return;
  }

  if (!isObjectRecord(output)) {
    failures.push('malformed manifest: output must be an object when present');
    return;
  }

  validateAllowedKeys(
    output,
    new Set(['filenamePrefix', 'splitBy', 'categories']),
    'output',
    failures
  );

  if (!isNonEmptyString(output.filenamePrefix)) {
    failures.push('malformed manifest: output.filenamePrefix must be a non-empty string');
  } else if (!isSanitizedFilenameSegment(output.filenamePrefix)) {
    failures.push(
      "malformed manifest: output.filenamePrefix must use only letters, digits, '.', '_', '-' with no leading/trailing dashes"
    );
  }

  // splitBy and categories are recorded (mutually exclusively) so refresh can
  // replay the exact output shape; both are optional for older manifests.
  if ('splitBy' in output && output.splitBy !== 'dirs') {
    failures.push("malformed manifest: output.splitBy must be 'dirs' when present");
  }

  if ('categories' in output) {
    validateSourceDocsOutputCategories(output.categories, failures);
  }

  if ('splitBy' in output && 'categories' in output) {
    failures.push(
      'malformed manifest: output.splitBy and output.categories are mutually exclusive'
    );
  }
}

function validateSourceDocsOutputCategories(categories: unknown, failures: string[]): void {
  if (!isObjectRecord(categories)) {
    failures.push('malformed manifest: output.categories must be an object when present');
    return;
  }

  validateAllowedKeys(
    categories,
    new Set(['categories', 'fallback']),
    'output.categories',
    failures
  );

  const definitions = categories.categories;

  if (!Array.isArray(definitions) || definitions.length === 0) {
    failures.push('malformed manifest: output.categories.categories must be a non-empty array');
  } else {
    for (const [index, definition] of definitions.entries()) {
      const label = `output.categories.categories[${index}]`;

      if (!isObjectRecord(definition)) {
        failures.push(`malformed manifest: ${label} must be an object`);
        continue;
      }

      validateAllowedKeys(definition, new Set(['id', 'title', 'include']), label, failures);

      if (!isNonEmptyString(definition.id)) {
        failures.push(`malformed manifest: ${label}.id must be a non-empty string`);
      }

      if (!isNonEmptyString(definition.title)) {
        failures.push(`malformed manifest: ${label}.title must be a non-empty string`);
      }

      if (
        !Array.isArray(definition.include) ||
        definition.include.length === 0 ||
        !definition.include.every((glob) => isNonEmptyString(glob))
      ) {
        failures.push(
          `malformed manifest: ${label}.include must be a non-empty array of non-empty strings`
        );
      }
    }
  }

  if (!isNonEmptyString(categories.fallback)) {
    failures.push('malformed manifest: output.categories.fallback must be a non-empty string');
  }
}

/**
 * Every llm-docs text output is named `<prefix>-...-llms.txt` by the universal
 * formatter: the combined -full slice, the reserved -toc slice, category
 * slices, and their collision-renamed variants all keep the prefix. A basename
 * that does not start with the recorded output.filenamePrefix therefore proves
 * the outputs were not generated with the recorded shape (for example a refresh
 * that fell back to a source-derived prefix), making shape drift detectable
 * from the manifest alone.
 */
function crossCheckGeneratedOutputFilenamePrefix(
  output: unknown,
  generatedOutputs: unknown[],
  failures: string[]
): void {
  if (!isObjectRecord(output)) {
    return;
  }

  const prefix = output.filenamePrefix;

  // A missing or malformed prefix is already reported by the output metadata
  // validation; the cross-check needs a trustworthy prefix to compare against.
  if (!isNonEmptyString(prefix) || !isSanitizedFilenameSegment(prefix)) {
    return;
  }

  for (const [index, entry] of generatedOutputs.entries()) {
    if (!isObjectRecord(entry) || entry.kind !== 'llm-docs') {
      continue;
    }

    const path = entry.path;

    if (!isNonEmptyString(path)) {
      continue;
    }

    const basename = path.split('/').at(-1) ?? path;

    if (!basename.startsWith(`${prefix}-`)) {
      failures.push(
        `malformed manifest: generatedOutputs[${index}] basename '${basename}' does not carry the recorded output.filenamePrefix '${prefix}'`
      );
    }
  }
}

interface OutputHeaderProvenance {
  hasProvenanceSegments: boolean;
  hasLabelSegment: boolean;
  labelValue?: string;
  hasGitSegment: boolean;
  gitSegmentText?: string;
}

/**
 * Cross-check the manifest's self-reported provenance (source.git.commit,
 * source.label) against the hash-bound <SYSTEM> header of the primary generated
 * output. The manifest git/label block is otherwise unsigned; the header carries
 * the same values and cannot be edited without breaking the output's recorded
 * hash. A mismatch is pushed as an outputs-tier failure.
 *
 * Backward compatibility: outputs generated before header provenance stamping
 * (and v1 packs) carry no provenance segments on line 1. Those are skipped with
 * a note rather than failed.
 */
async function crossCheckManifestProvenanceAgainstOutputHeader(options: {
  manifestDir: string;
  source: Record<string, unknown>;
  generatedOutputs: unknown[];
  outputsClean: boolean;
  failures: string[];
  notes: string[];
}): Promise<void> {
  const { manifestDir, source, generatedOutputs, outputsClean, failures, notes } = options;

  const label = source.label;
  const git = source.git;
  const hasLabel = isNonEmptyString(label);
  const gitCommit =
    isObjectRecord(git) && isNonEmptyString(git.commit) ? git.commit : undefined;

  // Nothing self-reported to bind: no cross-check.
  if (!hasLabel && gitCommit === undefined) {
    return;
  }

  // The check binds to the HASH-BOUND primary output. If the outputs tier is not
  // clean, that output already failed (or a sibling did) and reading a possibly
  // tampered header proves nothing; the failure is already surfaced.
  if (!outputsClean) {
    return;
  }

  const primaryPath = findPrimaryGeneratedOutputPath(generatedOutputs);
  if (primaryPath === undefined) {
    return;
  }

  let firstLine: string;
  try {
    firstLine = await readFirstLine(resolve(manifestDir, primaryPath));
  } catch {
    // Unreadable primary output is an outputs-tier hash-check concern already
    // reported; do not double-report here.
    return;
  }

  const provenance = parseOutputHeaderProvenance(firstLine);

  if (!provenance.hasProvenanceSegments) {
    notes.push(
      'provenance cross-check skipped: the primary output header carries no provenance segments (pre-stamp or v1 pack)'
    );
    return;
  }

  if (hasLabel) {
    if (!provenance.hasLabelSegment) {
      failures.push(
        'manifest provenance does not match hash-bound output header: manifest records source.label but the output header carries no label segment'
      );
    } else if (provenance.labelValue !== label) {
      failures.push(
        'manifest provenance does not match hash-bound output header: source.label does not match the output header label'
      );
    }
  }

  if (gitCommit !== undefined) {
    if (!provenance.hasGitSegment) {
      failures.push(
        'manifest provenance does not match hash-bound output header: manifest records source.git.commit but the output header carries no git segment'
      );
    } else if (
      provenance.gitSegmentText === undefined ||
      !provenance.gitSegmentText.includes(gitCommit)
    ) {
      failures.push(
        'manifest provenance does not match hash-bound output header: source.git.commit does not appear in the output header'
      );
    }
  }
}

function findPrimaryGeneratedOutputPath(generatedOutputs: unknown[]): string | undefined {
  for (const output of generatedOutputs) {
    if (!isObjectRecord(output)) {
      continue;
    }

    const path = output.path;
    if (output.kind === 'llm-docs' && isNonEmptyString(path) && path.endsWith('-full-llms.txt')) {
      return path;
    }
  }

  return undefined;
}

async function readFirstLine(path: string): Promise<string> {
  // Bounded read: the header line is short; never load the whole pack.
  const handle = await open(path, 'r');

  try {
    const buffer = Buffer.alloc(65536);
    const { bytesRead } = await handle.read(buffer, 0, buffer.length, 0);
    const text = buffer.subarray(0, bytesRead).toString('utf-8');
    const newlineIndex = text.indexOf('\n');

    return newlineIndex === -1 ? text : text.slice(0, newlineIndex);
  } finally {
    await handle.close();
  }
}

/**
 * Parse the provenance segments the universal formatter appends inside the
 * line-1 `<SYSTEM>` tag: `<base> | label: <label> | source: <url>@<commit> ...`
 * (or `... | commit: <commit> ...` when there is no remote). The label segment,
 * when present, comes before the git segment, so the label value runs from
 * `label: ` up to the git marker (or end of the SYSTEM content). This tolerates a
 * literal `| ` inside an operator label as long as the git segment separator is
 * intact.
 */
function parseOutputHeaderProvenance(firstLine: string): OutputHeaderProvenance {
  const systemMatch = /<SYSTEM>([\s\S]*?)<\/SYSTEM>/.exec(firstLine);
  const systemContent = systemMatch?.[1] ?? firstLine;

  const gitMarker = firstGitSegmentMarker(systemContent);
  const labelMarker = ' | label: ';
  const labelIndex = systemContent.indexOf(labelMarker);

  const hasLabelSegment = labelIndex !== -1;
  const hasGitSegment = gitMarker !== undefined;

  let labelValue: string | undefined;
  if (hasLabelSegment) {
    const valueStart = labelIndex + labelMarker.length;
    const valueEnd =
      gitMarker !== undefined && gitMarker.index > valueStart
        ? gitMarker.index
        : systemContent.length;
    labelValue = systemContent.slice(valueStart, valueEnd);
  }

  const gitSegmentText =
    gitMarker === undefined
      ? undefined
      : systemContent.slice(gitMarker.index + ' | '.length);

  return {
    hasProvenanceSegments: hasLabelSegment || hasGitSegment,
    hasLabelSegment,
    ...(labelValue === undefined ? {} : { labelValue }),
    hasGitSegment,
    ...(gitSegmentText === undefined ? {} : { gitSegmentText }),
  };
}

function firstGitSegmentMarker(systemContent: string): { index: number } | undefined {
  const sourceIndex = systemContent.indexOf(' | source: ');
  const commitIndex = systemContent.indexOf(' | commit: ');
  const candidates = [sourceIndex, commitIndex].filter((index) => index !== -1);

  if (candidates.length === 0) {
    return undefined;
  }

  return { index: Math.min(...candidates) };
}

const SOURCE_DRIFT_MAX_LISTED_PATHS = 20;

async function rescanSourceDirectoryForAddedFiles(options: {
  sourcePath: string;
  resolvedFormat: string;
  excludeGlobs: unknown;
  recordedPaths: string[];
  failures: string[];
  notes: string[];
}): Promise<void> {
  const { sourcePath, resolvedFormat, excludeGlobs, recordedPaths, failures, notes } = options;

  // Without the recorded exclude set the expected file set cannot be soundly
  // recomputed: a file the original --exclude would have dropped is
  // indistinguishable from real drift. Old manifests skip with a note.
  if (excludeGlobs === undefined) {
    notes.push(
      'source added-file rescan skipped: this manifest predates recorded exclude globs (source.excludeGlobs), so the expected source file set cannot be soundly recomputed; regenerate to enable added-file detection'
    );
    return;
  }

  if (!Array.isArray(excludeGlobs) || !excludeGlobs.every((glob) => isNonEmptyString(glob))) {
    // Structural validation already failed the manifest in this case.
    return;
  }

  let discoveredPaths: string[];

  try {
    discoveredPaths = await scanSourceDocsDirectorySelection({
      sourcePath,
      resolvedFormat,
      exclude: excludeGlobs,
    });
  } catch (error) {
    failures.push(`source: added-file rescan of ${sourcePath} failed: ${errorMessage(error)}`);
    return;
  }

  const recorded = new Set(recordedPaths);
  const added = discoveredPaths
    .filter((path) => !recorded.has(path))
    .sort(compareStringsByCodeUnit);

  if (added.length === 0) {
    return;
  }

  const shown = added.slice(0, SOURCE_DRIFT_MAX_LISTED_PATHS);
  const remainder = added.length - shown.length;

  failures.push(
    `source drift: ${added.length} file(s) added since generation: ${shown.join(', ')}${
      remainder > 0 ? ` (+${remainder} more)` : ''
    }`
  );
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await lstat(path);
    return true;
  } catch {
    return false;
  }
}
interface SourceDocsParserPluginRecord {
  manifestPath: string;
  resolvedManifestPath: string;
  manifestByteSize: number;
  manifestHash: string;
  name: string;
  version: string;
  module: {
    path: string;
    resolvedPath: string;
  };
  format: ParserPluginFormatMetadata;
}
function validateSourceDocsParserMetadata(
  parser: Record<string, unknown>,
  sourceResolvedFormat: unknown,
  parserPluginFormatId: string | undefined,
  failures: string[]
): void {
  const parserFormat = parser.format;

  if (!isNonEmptyString(parser.name)) {
    failures.push('malformed manifest: parser.name must be a non-empty string');
  }

  if (!isNonEmptyString(parser.version)) {
    failures.push('malformed manifest: parser.version must be a non-empty string');
  }

  if (!isNonEmptyString(parserFormat)) {
    failures.push('malformed manifest: parser.format must be a supported source format');
    return;
  }

  if (parserPluginFormatId === undefined && !SOURCE_DOCS_RESOLVED_FORMATS.has(parserFormat)) {
    failures.push('malformed manifest: parser.format must be a supported source format');
    return;
  }

  if (parserPluginFormatId !== undefined && parserFormat !== parserPluginFormatId) {
    failures.push('malformed manifest: parser.format must match parser.plugin.format.id');
  }

  if (isNonEmptyString(sourceResolvedFormat) && parserFormat !== sourceResolvedFormat) {
    failures.push('malformed manifest: parser.format must match source.resolvedFormat');
  }
}
function validateSourceDocsParserPluginMetadata(
  plugin: unknown,
  failures: string[],
  fileChecks: FileCheck[]
): SourceDocsParserPluginRecord | undefined {
  if (plugin === undefined) {
    return undefined;
  }

  if (!isObjectRecord(plugin)) {
    failures.push('malformed manifest: parser.plugin must be an object when present');
    return undefined;
  }

  const manifestPath = plugin.manifestPath;
  const resolvedManifestPath = plugin.resolvedManifestPath;
  const manifestByteSize = plugin.manifestByteSize;
  const manifestHash = plugin.manifestHash;
  const moduleMetadata = plugin.module;
  const formatMetadata = plugin.format;
  const execution = plugin.execution;

  if (!isNonEmptyString(manifestPath)) {
    failures.push('malformed manifest: parser.plugin.manifestPath must be a non-empty string');
  }

  if (!isNonEmptyString(resolvedManifestPath)) {
    failures.push(
      'malformed manifest: parser.plugin.resolvedManifestPath must be a non-empty string'
    );
  } else if (!isAbsolute(resolvedManifestPath)) {
    failures.push('malformed manifest: parser.plugin.resolvedManifestPath must be absolute');
  }

  if (!isNonNegativeInteger(manifestByteSize)) {
    failures.push(
      'malformed manifest: parser.plugin.manifestByteSize must be a non-negative integer'
    );
  }

  if (!isSha256Hash(manifestHash)) {
    failures.push('malformed manifest: parser.plugin.manifestHash must be a sha256 hash');
  }

  if (!isNonEmptyString(plugin.name)) {
    failures.push('malformed manifest: parser.plugin.name must be a non-empty string');
  }

  if (!isNonEmptyString(plugin.version)) {
    failures.push('malformed manifest: parser.plugin.version must be a non-empty string');
  }

  const moduleRecord = validateSourceDocsParserPluginModuleMetadata(moduleMetadata, failures);
  const formatRecord = validateSourceDocsParserPluginFormatMetadata(formatMetadata, failures);
  validateSourceDocsParserPluginExecutionMetadata(execution, failures);

  if (
    isNonEmptyString(resolvedManifestPath) &&
    isAbsolute(resolvedManifestPath) &&
    isNonNegativeInteger(manifestByteSize) &&
    isSha256Hash(manifestHash)
  ) {
    fileChecks.push({
      label: 'parser.plugin.manifest',
      path: resolvedManifestPath,
      expectedByteSize: manifestByteSize,
      expectedHash: manifestHash,
    });
  }

  if (
    !isNonEmptyString(manifestPath) ||
    !isNonEmptyString(resolvedManifestPath) ||
    !isAbsolute(resolvedManifestPath) ||
    !isNonNegativeInteger(manifestByteSize) ||
    !isSha256Hash(manifestHash) ||
    !isNonEmptyString(plugin.name) ||
    !isNonEmptyString(plugin.version) ||
    moduleRecord === undefined ||
    formatRecord === undefined
  ) {
    return undefined;
  }

  return {
    manifestPath,
    resolvedManifestPath,
    manifestByteSize,
    manifestHash,
    name: plugin.name,
    version: plugin.version,
    module: moduleRecord,
    format: formatRecord,
  };
}
function validateSourceDocsParserPluginModuleMetadata(
  moduleMetadata: unknown,
  failures: string[]
): SourceDocsParserPluginRecord['module'] | undefined {
  if (!isObjectRecord(moduleMetadata)) {
    failures.push('malformed manifest: parser.plugin.module must be an object');
    return undefined;
  }

  const modulePath = moduleMetadata.path;
  const moduleResolvedPath = moduleMetadata.resolvedPath;
  let valid = true;

  if (!isNonEmptyString(modulePath)) {
    failures.push('malformed manifest: parser.plugin.module.path must be a non-empty string');
    valid = false;
  } else if (
    isUrlLikePath(modulePath) ||
    isAbsolute(modulePath) ||
    win32.isAbsolute(modulePath) ||
    hasEmptyOrParentPathSegment(modulePath)
  ) {
    failures.push('malformed manifest: parser.plugin.module.path must be relative');
    valid = false;
  }

  if (!isNonEmptyString(moduleResolvedPath)) {
    failures.push(
      'malformed manifest: parser.plugin.module.resolvedPath must be a non-empty string'
    );
    valid = false;
  } else if (!isAbsolute(moduleResolvedPath)) {
    failures.push('malformed manifest: parser.plugin.module.resolvedPath must be absolute');
    valid = false;
  }

  return valid && isNonEmptyString(modulePath) && isNonEmptyString(moduleResolvedPath)
    ? {
        path: modulePath,
        resolvedPath: moduleResolvedPath,
      }
    : undefined;
}
function validateSourceDocsParserPluginFormatMetadata(
  formatMetadata: unknown,
  failures: string[]
): ParserPluginFormatMetadata | undefined {
  if (!isObjectRecord(formatMetadata)) {
    failures.push('malformed manifest: parser.plugin.format must be an object');
    return undefined;
  }

  const formatId = formatMetadata.id;
  const extensions = formatMetadata.extensions;
  const mediaTypes = formatMetadata.mediaTypes;
  const directorySupport = formatMetadata.directorySupport;
  let valid = true;

  if (!isNonEmptyString(formatId) || !SOURCE_DOCS_PLUGIN_FORMAT_ID_PATTERN.test(formatId)) {
    failures.push("malformed manifest: parser.plugin.format.id must match '^[a-z][a-z0-9-]*$'");
    valid = false;
  }

  if (!isNonEmptyString(formatMetadata.displayName)) {
    failures.push(
      'malformed manifest: parser.plugin.format.displayName must be a non-empty string'
    );
    valid = false;
  }

  if (!Array.isArray(extensions) || extensions.length === 0) {
    failures.push('malformed manifest: parser.plugin.format.extensions must be a non-empty array');
    valid = false;
  } else if (!extensions.every((extension) => isNonEmptyString(extension))) {
    failures.push('malformed manifest: parser.plugin.format.extensions must contain only strings');
    valid = false;
  }

  let parsedMediaTypes: string[] | undefined;
  if (mediaTypes !== undefined) {
    parsedMediaTypes = validateOptionalStringArray(
      mediaTypes,
      'parser.plugin.format.mediaTypes',
      failures
    );

    if (parsedMediaTypes === undefined) {
      valid = false;
    }

    if (parsedMediaTypes?.some((mediaType) => mediaType.length === 0)) {
      failures.push(
        'malformed manifest: parser.plugin.format.mediaTypes must contain only non-empty strings'
      );
      valid = false;
    }
  }

  if (directorySupport !== undefined && typeof directorySupport !== 'boolean') {
    failures.push('malformed manifest: parser.plugin.format.directorySupport must be a boolean');
    valid = false;
  }

  return valid &&
    isNonEmptyString(formatId) &&
    SOURCE_DOCS_PLUGIN_FORMAT_ID_PATTERN.test(formatId) &&
    isNonEmptyString(formatMetadata.displayName) &&
    Array.isArray(extensions) &&
    extensions.length > 0 &&
    extensions.every((extension) => isNonEmptyString(extension))
    ? {
        id: formatId,
        displayName: formatMetadata.displayName,
        extensions,
        ...(parsedMediaTypes === undefined ? {} : { mediaTypes: parsedMediaTypes }),
        ...(typeof directorySupport === 'boolean' ? { directorySupport } : {}),
      }
    : undefined;
}
function validateSourceDocsParserPluginExecutionMetadata(
  execution: unknown,
  failures: string[]
): void {
  if (!isObjectRecord(execution)) {
    failures.push('malformed manifest: parser.plugin.execution must be an object');
    return;
  }

  if (execution.codeExecuted !== true) {
    failures.push('malformed manifest: parser.plugin.execution.codeExecuted must be true');
  }

  if (execution.trust !== 'trusted-local-code') {
    failures.push("malformed manifest: parser.plugin.execution.trust must be 'trusted-local-code'");
  }

  if (execution.sandboxed !== false) {
    failures.push('malformed manifest: parser.plugin.execution.sandboxed must be false');
  }

  if (!isNonEmptyString(execution.statement)) {
    failures.push(
      'malformed manifest: parser.plugin.execution.statement must be a non-empty string'
    );
  }
}
function validateSourceDocsParserPluginGeneratedOutputs(
  generatedOutputs: unknown[],
  failures: string[]
): void {
  for (const [index, output] of generatedOutputs.entries()) {
    if (!isObjectRecord(output)) {
      continue;
    }

    if (output.kind === SOURCE_DOCS_SEMANTIC_CHUNK_JSONL_KIND) {
      failures.push(
        `malformed manifest: generatedOutputs[${index}].kind must not be semantic-chunks-jsonl for parser.plugin source manifests`
      );
    }
  }
}
async function verifySourceDocsParserPluginManifestMetadata(
  recorded: SourceDocsParserPluginRecord,
  failures: string[]
): Promise<void> {
  try {
    const actualManifestFile = await describeFile(recorded.resolvedManifestPath);

    if (actualManifestFile.byteSize !== recorded.manifestByteSize) {
      failures.push(
        'parser.plugin.manifest: byte size does not match parser.plugin.manifestByteSize'
      );
    }

    if (actualManifestFile.hash !== recorded.manifestHash) {
      failures.push('parser.plugin.manifest: hash does not match parser.plugin.manifestHash');
    }
  } catch (error) {
    if (isFileNotFoundError(error)) {
      failures.push(`parser.plugin.manifest: missing file at ${recorded.resolvedManifestPath}`);
      return;
    }

    failures.push(
      `parser.plugin.manifest: cannot read ${recorded.resolvedManifestPath}: ${errorMessage(error)}`
    );
    return;
  }

  const validation = await validateParserPluginManifestFile({
    manifestPath: recorded.resolvedManifestPath,
  });

  if (!validation.valid || validation.manifest === undefined) {
    const details = validation.errors.map((error) => `${error.path}: ${error.message}`).join('; ');

    failures.push(`parser.plugin.manifest: recorded plugin manifest is invalid: ${details}`);
    return;
  }

  compareParserPluginManifestMetadata(recorded, validation.manifest, failures);
}
function compareParserPluginManifestMetadata(
  recorded: SourceDocsParserPluginRecord,
  manifest: ParserPluginManifestMetadata,
  failures: string[]
): void {
  if (recorded.name !== manifest.name) {
    failures.push('parser.plugin.name must match parser plugin manifest name');
  }

  if (recorded.version !== manifest.version) {
    failures.push('parser.plugin.version must match parser plugin manifest version');
  }

  if (recorded.module.path !== manifest.module) {
    failures.push('parser.plugin.module.path must match parser plugin manifest module');
  }

  const selectedFormat = manifest.formats.find((format) => format.id === recorded.format.id);

  if (selectedFormat === undefined) {
    failures.push('parser.plugin.format.id must match a format declared by the plugin manifest');
    return;
  }

  compareParserPluginFormatMetadata(recorded.format, selectedFormat, failures);
}
function compareParserPluginFormatMetadata(
  recorded: ParserPluginFormatMetadata,
  selectedFormat: ParserPluginFormatMetadata,
  failures: string[]
): void {
  if (recorded.displayName !== selectedFormat.displayName) {
    failures.push(
      'parser.plugin.format.displayName must match parser plugin manifest selected format'
    );
  }

  if (!stringArraysEqual(recorded.extensions, selectedFormat.extensions)) {
    failures.push(
      'parser.plugin.format.extensions must match parser plugin manifest selected format'
    );
  }

  if (!optionalStringArraysEqual(recorded.mediaTypes, selectedFormat.mediaTypes)) {
    failures.push(
      'parser.plugin.format.mediaTypes must match parser plugin manifest selected format'
    );
  }

  if (recorded.directorySupport !== selectedFormat.directorySupport) {
    failures.push(
      'parser.plugin.format.directorySupport must match parser plugin manifest selected format'
    );
  }
}
function validateSourceDocsFormatterMetadata(
  formatter: Record<string, unknown>,
  failures: string[]
): void {
  if (formatter.name !== SOURCE_DOCS_FORMATTER_NAME) {
    failures.push(`malformed manifest: formatter.name must be ${SOURCE_DOCS_FORMATTER_NAME}`);
  }

  if (!isNonEmptyString(formatter.version)) {
    failures.push('malformed manifest: formatter.version must be a non-empty string');
  }

  if (formatter.format !== SOURCE_DOCS_FORMATTER_FORMAT) {
    failures.push(`malformed manifest: formatter.format must be ${SOURCE_DOCS_FORMATTER_FORMAT}`);
  }
}
function validateSourceDocsSemanticChunkIndexes(options: {
  semanticChunkIndexes: unknown;
  generatedOutputs: unknown[];
  manifestDir: string;
  failures: string[];
}): SemanticChunkManifestIndex[] {
  const { semanticChunkIndexes, generatedOutputs, manifestDir, failures } = options;

  if (semanticChunkIndexes === undefined) {
    // A semantic-chunks-jsonl output with no index would leave its chunk
    // metadata (ordinals, per-chunk hashes, warning counts) unverified, so an
    // omitted index must fail rather than silently pass when such an output
    // exists.
    if (sourceDocsSemanticChunkOutputPaths(generatedOutputs, manifestDir).size > 0) {
      failures.push(
        'malformed manifest: semanticChunkIndexes is required when a semantic-chunks-jsonl output is present'
      );
    }
    return [];
  }

  if (!Array.isArray(semanticChunkIndexes)) {
    failures.push('malformed manifest: semanticChunkIndexes must be an array when present');
    return [];
  }

  const expectedChunkOutputPaths = sourceDocsSemanticChunkOutputPaths(
    generatedOutputs,
    manifestDir
  );
  const entries: SemanticChunkManifestIndex[] = [];
  const seenPaths = new Set<string>();

  for (const [index, chunkIndex] of semanticChunkIndexes.entries()) {
    const label = `semanticChunkIndexes[${index}]`;

    if (!isObjectRecord(chunkIndex)) {
      failures.push(`malformed manifest: ${label} must be an object`);
      continue;
    }

    validateAllowedKeys(chunkIndex, SOURCE_DOCS_SEMANTIC_CHUNK_INDEX_KEYS, label, failures);

    const outputPath = chunkIndex.path;
    const format = chunkIndex.format;
    const chunkCount = chunkIndex.chunkCount;
    const aggregateHash = chunkIndex.aggregateHash;
    const warningCount = chunkIndex.warningCount;
    const chunks = chunkIndex.chunks;
    const chunkEntries: SemanticChunkManifestIndexChunk[] = [];

    if (!isNonEmptyString(outputPath)) {
      failures.push(`malformed manifest: ${label}.path must be a non-empty string`);
    } else if (isAbsolute(outputPath)) {
      failures.push(`malformed manifest: ${label}.path must be relative: ${outputPath}`);
    } else if (!isInsideDirectory(manifestDir, resolve(manifestDir, outputPath))) {
      failures.push(`malformed manifest: ${label}.path escapes manifest directory: ${outputPath}`);
    } else if (!expectedChunkOutputPaths.has(outputPath)) {
      failures.push(
        `malformed manifest: ${label}.path must reference a semantic-chunks-jsonl generated output`
      );
    } else if (seenPaths.has(outputPath)) {
      failures.push(`malformed manifest: duplicate semantic chunk index path: ${outputPath}`);
    } else {
      seenPaths.add(outputPath);
    }

    if (format !== 'jsonl') {
      failures.push(`malformed manifest: ${label}.format must be jsonl`);
    }

    if (!isNonNegativeInteger(chunkCount)) {
      failures.push(`malformed manifest: ${label}.chunkCount must be a non-negative integer`);
    }

    if (!isSha256Hash(aggregateHash)) {
      failures.push(`malformed manifest: ${label}.aggregateHash must be a sha256 hash`);
    }

    if (!isNonNegativeInteger(warningCount)) {
      failures.push(`malformed manifest: ${label}.warningCount must be a non-negative integer`);
    }

    if (!Array.isArray(chunks)) {
      failures.push(`malformed manifest: ${label}.chunks must be an array`);
    } else {
      for (const [chunkEntryIndex, chunkEntry] of chunks.entries()) {
        const chunkLabel = `${label}.chunks[${chunkEntryIndex}]`;
        const normalizedChunk = validateSourceDocsSemanticChunkIndexChunk({
          chunkEntry,
          label: chunkLabel,
          expectedOrder: chunkEntryIndex + 1,
          failures,
        });

        if (normalizedChunk !== undefined) {
          chunkEntries.push(normalizedChunk);
        }
      }
    }

    if (Array.isArray(chunks) && isNonNegativeInteger(chunkCount) && chunks.length !== chunkCount) {
      failures.push(`malformed manifest: ${label}.chunkCount must match chunks length`);
    }

    if (
      isNonNegativeInteger(warningCount) &&
      Array.isArray(chunks) &&
      chunkEntries.length === chunks.length
    ) {
      const actualWarningCount = chunkEntries.reduce(
        (total, chunk) => total + chunk.warningCount,
        0
      );

      if (warningCount !== actualWarningCount) {
        failures.push(`malformed manifest: ${label}.warningCount must match chunk warning counts`);
      }
    }

    if (
      isNonEmptyString(outputPath) &&
      !isAbsolute(outputPath) &&
      isInsideDirectory(manifestDir, resolve(manifestDir, outputPath)) &&
      format === 'jsonl' &&
      isNonNegativeInteger(chunkCount) &&
      isSha256Hash(aggregateHash) &&
      isNonNegativeInteger(warningCount) &&
      Array.isArray(chunks) &&
      chunkEntries.length === chunks.length
    ) {
      const normalizedIndex: SemanticChunkManifestIndex = {
        path: outputPath,
        format,
        chunkCount,
        aggregateHash,
        warningCount,
        chunks: chunkEntries,
      };
      const actualAggregateHash = hashSemanticChunkManifestIndex({
        path: normalizedIndex.path,
        format: normalizedIndex.format,
        chunkCount: normalizedIndex.chunkCount,
        warningCount: normalizedIndex.warningCount,
        chunks: normalizedIndex.chunks,
      });

      if (normalizedIndex.aggregateHash !== actualAggregateHash) {
        failures.push(
          `malformed manifest: ${label}.aggregateHash must match semantic chunk index metadata`
        );
      }

      entries.push(normalizedIndex);
    }
  }

  if (
    semanticChunkIndexes.length === entries.length &&
    expectedChunkOutputPaths.size !== entries.length
  ) {
    failures.push(
      'malformed manifest: semanticChunkIndexes must contain one entry per semantic-chunks-jsonl generated output'
    );
  }

  return entries;
}
function validateSourceDocsSemanticChunkIndexChunk(options: {
  chunkEntry: unknown;
  label: string;
  expectedOrder: number;
  failures: string[];
}): SemanticChunkManifestIndexChunk | undefined {
  const { chunkEntry, label, expectedOrder, failures } = options;

  if (!isObjectRecord(chunkEntry)) {
    failures.push(`malformed manifest: ${label} must be an object`);
    return undefined;
  }

  validateAllowedKeys(chunkEntry, SOURCE_DOCS_SEMANTIC_CHUNK_INDEX_CHUNK_KEYS, label, failures);

  const id = chunkEntry.id;
  const order = chunkEntry.order;
  const title = chunkEntry.title;
  const path = chunkEntry.path;
  const nodePath = chunkEntry.nodePath;
  const contentHash = chunkEntry.contentHash;
  const characterCount = chunkEntry.characterCount;
  const estimatedTokenCount = chunkEntry.estimatedTokenCount;
  const sourceFormat = chunkEntry.sourceFormat;
  const sourcePath = chunkEntry.sourcePath;
  const warningCount = chunkEntry.warningCount;

  if (!isNonEmptyString(id)) {
    failures.push(`malformed manifest: ${label}.id must be a non-empty string`);
  }

  if (!isPositiveInteger(order)) {
    failures.push(`malformed manifest: ${label}.order must be a positive integer`);
  } else if (order !== expectedOrder) {
    failures.push(`malformed manifest: ${label}.order must match chunk index order`);
  }

  if (!isNonEmptyString(title)) {
    failures.push(`malformed manifest: ${label}.title must be a non-empty string`);
  }

  if (!isStringArray(path)) {
    failures.push(`malformed manifest: ${label}.path must be a string array`);
  }

  if (!isStringArray(nodePath)) {
    failures.push(`malformed manifest: ${label}.nodePath must be a string array`);
  }

  if (!isUnprefixedSha256Hash(contentHash)) {
    failures.push(`malformed manifest: ${label}.contentHash must be a sha256 hex digest`);
  }

  if (!isNonNegativeInteger(characterCount)) {
    failures.push(`malformed manifest: ${label}.characterCount must be a non-negative integer`);
  }

  if (!isNonNegativeInteger(estimatedTokenCount)) {
    failures.push(
      `malformed manifest: ${label}.estimatedTokenCount must be a non-negative integer`
    );
  }

  if ('sourceFormat' in chunkEntry && !isNonEmptyString(sourceFormat)) {
    failures.push(`malformed manifest: ${label}.sourceFormat must be a non-empty string`);
  }

  if ('sourcePath' in chunkEntry && !isNonEmptyString(sourcePath)) {
    failures.push(`malformed manifest: ${label}.sourcePath must be a non-empty string`);
  }

  if (!isNonNegativeInteger(warningCount)) {
    failures.push(`malformed manifest: ${label}.warningCount must be a non-negative integer`);
  }

  if (
    !isNonEmptyString(id) ||
    !isPositiveInteger(order) ||
    !isNonEmptyString(title) ||
    !isStringArray(path) ||
    !isStringArray(nodePath) ||
    !isUnprefixedSha256Hash(contentHash) ||
    !isNonNegativeInteger(characterCount) ||
    !isNonNegativeInteger(estimatedTokenCount) ||
    ('sourceFormat' in chunkEntry && !isNonEmptyString(sourceFormat)) ||
    ('sourcePath' in chunkEntry && !isNonEmptyString(sourcePath)) ||
    !isNonNegativeInteger(warningCount)
  ) {
    return undefined;
  }

  const normalizedChunk: SemanticChunkManifestIndexChunk = {
    id,
    order,
    title,
    path,
    nodePath,
    contentHash,
    characterCount,
    estimatedTokenCount,
    warningCount,
  };

  if (typeof sourceFormat === 'string') {
    normalizedChunk.sourceFormat = sourceFormat;
  }

  if (typeof sourcePath === 'string') {
    normalizedChunk.sourcePath = sourcePath;
  }

  return normalizedChunk;
}
async function verifySourceDocsSemanticChunkIndexes(options: {
  manifestDir: string;
  semanticChunkIndexes: SemanticChunkManifestIndex[];
  failures: string[];
}): Promise<void> {
  for (const semanticChunkIndex of options.semanticChunkIndexes) {
    let actualIndex: SemanticChunkManifestIndex;

    try {
      actualIndex = await buildSemanticChunkJsonlManifestIndex({
        manifestDir: options.manifestDir,
        outputPath: semanticChunkIndex.path,
      });
    } catch (error) {
      options.failures.push(
        `semantic chunk index ${semanticChunkIndex.path}: ${errorMessage(error)}`
      );
      continue;
    }

    if (!semanticChunkManifestIndexesEqual(semanticChunkIndex, actualIndex)) {
      options.failures.push(
        `semantic chunk index ${semanticChunkIndex.path}: manifest metadata does not match JSONL records`
      );
    }
  }
}
function sourceDocsSemanticChunkOutputPaths(
  generatedOutputs: unknown[],
  manifestDir: string
): Set<string> {
  const paths = new Set<string>();

  for (const output of generatedOutputs) {
    if (!isObjectRecord(output) || output.kind !== SOURCE_DOCS_SEMANTIC_CHUNK_JSONL_KIND) {
      continue;
    }

    const outputPath = output.path;

    if (
      isNonEmptyString(outputPath) &&
      !isAbsolute(outputPath) &&
      isInsideDirectory(manifestDir, resolve(manifestDir, outputPath))
    ) {
      paths.add(outputPath);
    }
  }

  return paths;
}
function validateSourceDocsPresetMetadata(preset: unknown, failures: string[]): void {
  for (const failure of validateSourceDocsPresetContract(preset)) {
    failures.push(`malformed manifest: ${failure}`);
  }
}

export function validateSourceDocsPresetContract(preset: unknown): string[] {
  const failures: string[] = [];

  if (preset === undefined) {
    return failures;
  }

  if (!isObjectRecord(preset)) {
    failures.push('preset must be an object when present');
    return failures;
  }

  if (preset.name !== SOURCE_DOCS_SWIFT_BOOK_PRESET_NAME) {
    failures.push(`preset.name must be ${SOURCE_DOCS_SWIFT_BOOK_PRESET_NAME}`);
  }

  if (!isNonEmptyString(preset.configPath)) {
    failures.push('preset.configPath must be a non-empty string');
  }

  if (!isNonEmptyString(preset.displayName)) {
    failures.push('preset.displayName must be a non-empty string');
  }

  const defaults = preset.defaults;
  if (!isObjectRecord(defaults)) {
    failures.push('preset.defaults must be an object');
  } else {
    if (defaults.format !== 'markdown') {
      failures.push('preset.defaults.format must be markdown');
    }

    if (!isNonEmptyString(defaults.filenamePrefix)) {
      failures.push('preset.defaults.filenamePrefix must be a non-empty string');
    }

    if (!isNonEmptyString(defaults.title)) {
      failures.push('preset.defaults.title must be a non-empty string');
    }

    if (!isNonEmptyString(defaults.systemPrompt)) {
      failures.push('preset.defaults.systemPrompt must be a non-empty string');
    } else {
      const unsupportedPromptClaims = findUnsupportedPresetPromptClaims(defaults.systemPrompt);

      if (unsupportedPromptClaims.length > 0) {
        failures.push(
          `preset.defaults.systemPrompt must not claim ${formatAllowedOutputKinds(new Set(unsupportedPromptClaims))}`
        );
      }
    }

    if (
      'outputFormats' in defaults &&
      (!Array.isArray(defaults.outputFormats) ||
        !defaults.outputFormats.every((format) => isNonEmptyString(format)))
    ) {
      failures.push(
        'preset.defaults.outputFormats must be an array of non-empty strings when present'
      );
    }
  }

  const metadata = preset.metadata;
  if (!isObjectRecord(metadata)) {
    failures.push('preset.metadata must be an object');
  } else {
    for (const [field, expectedValue] of Object.entries(SOURCE_DOCS_SWIFT_BOOK_PRESET_METADATA)) {
      if (metadata[field] !== expectedValue) {
        failures.push(`preset.metadata.${field} must be ${expectedValue}`);
      }
    }
  }

  if (!Array.isArray(preset.limitations)) {
    failures.push('preset.limitations must be an array');
    return failures;
  }

  if (!preset.limitations.every((limitation) => isNonEmptyString(limitation))) {
    failures.push('preset.limitations must contain only non-empty strings');
    return failures;
  }

  for (const limitation of SOURCE_DOCS_SWIFT_BOOK_PRESET_LIMITATIONS) {
    if (!preset.limitations.includes(limitation)) {
      failures.push(`preset.limitations must include "${limitation}"`);
    }
  }

  return failures;
}
function findUnsupportedPresetPromptClaims(prompt: string): string[] {
  const normalizedPrompt = prompt.toLowerCase().replace(/[-_]+/g, ' ').replace(/\s+/g, ' ').trim();
  const claims: string[] = [];

  if (/\b(complete|completeness|comprehensive)\b/.test(normalizedPrompt)) {
    claims.push('completeness');
  }

  if (/\bsource truth\b/.test(normalizedPrompt)) {
    claims.push('source truth');
  }

  if (/\b(verified|verification|validated|validation)\b/.test(normalizedPrompt)) {
    claims.push('source verification');
  }

  if (/\b(authoritative|authority|official)\b/.test(normalizedPrompt)) {
    claims.push('authority or official status');
  }

  return claims;
}
interface SourceFileEntry {
  path: string;
  resolvedPath: string;
  byteSize: number;
  hash: string;
  format: string;
}
function validateSourceFiles(options: {
  sourceFiles: unknown[];
  sourcePath: unknown;
  sourceType: unknown;
  sourceResolvedFormat: unknown;
  failures: string[];
  fileChecks: FileCheck[];
}): SourceFileEntry[] {
  const { sourceFiles, sourcePath, sourceType, sourceResolvedFormat, failures, fileChecks } =
    options;
  const sourceFileEntries: SourceFileEntry[] = [];
  const sourceRoot =
    isNonEmptyString(sourcePath) && isAbsolute(sourcePath) ? sourcePath : undefined;
  const trustedRoot =
    sourceRoot === undefined
      ? undefined
      : sourceType === 'directory'
        ? sourceRoot
        : dirname(sourceRoot);

  for (const [index, sourceFile] of sourceFiles.entries()) {
    const label = `sourceFiles[${index}]`;

    if (!isObjectRecord(sourceFile)) {
      failures.push(`malformed manifest: ${label} must be an object`);
      continue;
    }

    const sourceFilePath = sourceFile.path;
    const sourceFileResolvedPath = sourceFile.resolvedPath;
    const sourceFileByteSize = sourceFile.byteSize;
    const sourceFileHash = sourceFile.hash;
    const sourceFileLineCount = sourceFile.lineCount;
    const sourceFileEstimatedTokenCount = sourceFile.estimatedTokenCount;
    const sourceFileFormat = sourceFile.format;

    if (!isNonEmptyString(sourceFilePath)) {
      failures.push(`malformed manifest: ${label}.path must be a non-empty string`);
    } else if (isAbsolute(sourceFilePath)) {
      failures.push(`malformed manifest: ${label}.path must be relative: ${sourceFilePath}`);
    } else if (
      sourceRoot !== undefined &&
      sourceType === 'directory' &&
      !isInsideDirectory(sourceRoot, resolve(sourceRoot, sourceFilePath))
    ) {
      failures.push(`malformed manifest: ${label}.path escapes source root: ${sourceFilePath}`);
    }

    if (!isNonEmptyString(sourceFileResolvedPath)) {
      failures.push(`malformed manifest: ${label}.resolvedPath must be a non-empty string`);
    } else if (!isAbsolute(sourceFileResolvedPath)) {
      failures.push(`malformed manifest: ${label}.resolvedPath must be absolute`);
    } else if (
      sourceRoot !== undefined &&
      sourceType === 'directory' &&
      !isInsideDirectory(sourceRoot, sourceFileResolvedPath)
    ) {
      failures.push(
        `malformed manifest: ${label}.resolvedPath escapes source root: ${sourceFileResolvedPath}`
      );
    }

    if (
      sourceRoot !== undefined &&
      isNonEmptyString(sourceFilePath) &&
      !isAbsolute(sourceFilePath) &&
      isNonEmptyString(sourceFileResolvedPath) &&
      isAbsolute(sourceFileResolvedPath) &&
      isSourceDocsSourceType(sourceType)
    ) {
      const expectedResolvedPath =
        sourceType === 'directory'
          ? resolve(sourceRoot, sourceFilePath)
          : resolve(dirname(sourceRoot), sourceFilePath);

      if (expectedResolvedPath !== sourceFileResolvedPath) {
        failures.push(
          `malformed manifest: ${label}.resolvedPath must match ${label}.path under source.resolvedPath`
        );
      }

      if (sourceType === 'file' && sourceFileResolvedPath !== sourceRoot) {
        failures.push(
          `malformed manifest: ${label}.resolvedPath must match source.resolvedPath for file sources`
        );
      }
    }

    if (!isNonNegativeInteger(sourceFileByteSize)) {
      failures.push(`malformed manifest: ${label}.byteSize must be a non-negative integer`);
    }

    if (!isSha256Hash(sourceFileHash)) {
      failures.push(`malformed manifest: ${label}.hash must be a sha256 hash`);
    }

    if (!isNonNegativeInteger(sourceFileLineCount)) {
      failures.push(`malformed manifest: ${label}.lineCount must be a non-negative integer`);
    }

    if (!isNonNegativeInteger(sourceFileEstimatedTokenCount)) {
      failures.push(
        `malformed manifest: ${label}.estimatedTokenCount must be a non-negative integer`
      );
    }

    if (!isNonEmptyString(sourceFileFormat)) {
      failures.push(`malformed manifest: ${label}.format must be a non-empty string`);
    } else if (
      isNonEmptyString(sourceResolvedFormat) &&
      sourceFileFormat !== sourceResolvedFormat
    ) {
      failures.push(`malformed manifest: ${label}.format must match source.resolvedFormat`);
    }

    if (
      isNonEmptyString(sourceFilePath) &&
      !isAbsolute(sourceFilePath) &&
      isNonEmptyString(sourceFileResolvedPath) &&
      isAbsolute(sourceFileResolvedPath) &&
      isNonNegativeInteger(sourceFileByteSize) &&
      isSha256Hash(sourceFileHash) &&
      isNonEmptyString(sourceFileFormat)
    ) {
      sourceFileEntries.push({
        path: sourceFilePath,
        resolvedPath: sourceFileResolvedPath,
        byteSize: sourceFileByteSize,
        hash: sourceFileHash,
        format: sourceFileFormat,
      });
      const fileCheck: FileCheck = {
        label,
        path: sourceFileResolvedPath,
        expectedByteSize: sourceFileByteSize,
        expectedHash: sourceFileHash,
        rejectSymlink: true,
      };

      if (
        isNonNegativeInteger(sourceFileLineCount) &&
        isNonNegativeInteger(sourceFileEstimatedTokenCount)
      ) {
        fileCheck.expectedLineCount = sourceFileLineCount;
        fileCheck.expectedEstimatedTokenCount = sourceFileEstimatedTokenCount;
      }

      if (trustedRoot !== undefined) {
        fileCheck.trustedRoot = trustedRoot;
      }

      fileChecks.push(fileCheck);
    }
  }

  return sourceFileEntries;
}
