/**
 * Verifier and validators for source-docs manifests.
 */

import { dirname, isAbsolute, resolve, win32 } from 'node:path';

import {
  errorMessage,
  isFileNotFoundError,
  isNonEmptyString,
  isNonNegativeInteger,
  isObjectRecord,
} from '../../../utils/guards.js';
import { isSha256Hash, isUnprefixedSha256Hash } from '../../../utils/hash.js';
import { aggregateSourceFilesHash } from '../../../utils/source-files-hash.js';
import {
  buildSemanticChunkJsonlManifestIndex,
  hashSemanticChunkManifestIndex,
  semanticChunkManifestIndexesEqual,
  type SemanticChunkManifestIndex,
  type SemanticChunkManifestIndexChunk,
} from '../../semantic-chunk-index.js';
import {
  validateParserPluginManifestFile,
  type ParserPluginFormatMetadata,
  type ParserPluginManifestMetadata,
} from '../../parser-plugin-manifest.js';
import {
  SOURCE_DOCS_FORMATTER_FORMAT,
  SOURCE_DOCS_FORMATTER_NAME,
  SOURCE_DOCS_FORMAT_HINTS,
  SOURCE_DOCS_GENERATED_OUTPUT_KINDS,
  SOURCE_DOCS_MODE,
  SOURCE_DOCS_PLUGIN_FORMAT_ID_PATTERN,
  SOURCE_DOCS_RESOLVED_FORMATS,
  SOURCE_DOCS_SEMANTIC_CHUNK_INDEX_CHUNK_KEYS,
  SOURCE_DOCS_SEMANTIC_CHUNK_INDEX_KEYS,
  SOURCE_DOCS_SEMANTIC_CHUNK_JSONL_KIND,
  SOURCE_DOCS_SOURCE_TYPES,
  SOURCE_DOCS_SWIFT_BOOK_PRESET_LIMITATIONS,
  SOURCE_DOCS_SWIFT_BOOK_PRESET_METADATA,
  SOURCE_DOCS_SWIFT_BOOK_PRESET_NAME,
} from '../constants.js';
import {
  formatAllowedOutputKinds,
  isInsideDirectory,
  isPositiveInteger,
  isSourceDocsSourceType,
  isStringArray,
} from '../predicates.js';
import {
  optionalStringArraysEqual,
  stringArraysEqual,
  validateAllowedKeys,
  validateOptionalStringArray,
} from '../field-validators.js';
import {
  describeFile,
  hasEmptyOrParentPathSegment,
  isUrlLikePath,
  verifyFile,
  verifyPathType,
} from '../fs-verify.js';
import type { FileCheck, PathTypeCheck } from '../fs-verify.js';
import type { VerifyGenerationManifestResult } from '../types.js';
import { validateRequiredManifestContract } from '../contract.js';
import { validateRequiredInputProvenance } from '../provenance.js';
import { validateRequiredArtifactSummary } from '../artifact-summary.js';
import { validateRefreshProvenance } from '../refresh-provenance.js';
import { validateGeneratedOutputs, validateGeneratorMetadata } from './shared.js';

export async function verifySourceDocsManifest(
  manifestPath: string,
  manifest: Record<string, unknown>
): Promise<VerifyGenerationManifestResult> {
  const failures: string[] = [];
  const manifestDir = dirname(manifestPath);
  const generator = manifest.generator;
  const source = manifest.source;
  const sourceFiles = manifest.sourceFiles;
  const parser = manifest.parser;
  const formatter = manifest.formatter;
  const generatedOutputs = manifest.generatedOutputs;
  const semanticChunkIndexes = manifest.semanticChunkIndexes;
  const preset = manifest.preset;

  if (!isObjectRecord(generator)) {
    failures.push('malformed manifest: missing generator object');
  } else {
    validateGeneratorMetadata(generator, failures);
  }

  if (!isObjectRecord(source)) {
    failures.push('malformed manifest: missing source object');
  }

  if (!Array.isArray(sourceFiles)) {
    failures.push('malformed manifest: missing sourceFiles array');
  }

  if (!isObjectRecord(parser)) {
    failures.push('malformed manifest: missing parser object');
  }

  if (!isObjectRecord(formatter)) {
    failures.push('malformed manifest: missing formatter object');
  }

  if (!Array.isArray(generatedOutputs)) {
    failures.push('malformed manifest: missing generatedOutputs array');
  }

  const hasParserPluginMetadata =
    isObjectRecord(parser) && (parser as Record<string, unknown>).plugin !== undefined;

  if (manifest.refresh !== undefined) {
    if (hasParserPluginMetadata) {
      failures.push(
        'malformed manifest: refresh is supported for local-source-docs manifests only when generated by the built-in parser'
      );
    } else {
      validateRefreshProvenance(manifest.refresh, SOURCE_DOCS_MODE, failures);
    }
  }

  if (failures.length > 0) {
    return {
      manifestPath,
      checkedFiles: 0,
      failures,
    };
  }

  const fileChecks: FileCheck[] = [];
  const pathTypeChecks: PathTypeCheck[] = [];
  const sourceRecord = source as Record<string, unknown>;
  const sourceFileRecords = sourceFiles as unknown[];
  const parserRecord = parser as Record<string, unknown>;
  const formatterRecord = formatter as Record<string, unknown>;
  const outputRecords = generatedOutputs as unknown[];
  const sourceInput = sourceRecord.input;
  const sourcePath = sourceRecord.resolvedPath;
  const sourceType = sourceRecord.type;
  const sourceFormatHint = sourceRecord.formatHint;
  const sourceResolvedFormat = sourceRecord.resolvedFormat;
  const sourceByteSize = sourceRecord.byteSize;
  const sourceHash = sourceRecord.hash;
  const sourceFileCount = sourceRecord.fileCount;
  const sourceAggregateHash = sourceRecord.aggregateHash;
  const parserPluginMetadata = validateSourceDocsParserPluginMetadata(
    parserRecord.plugin,
    failures,
    fileChecks
  );
  const parserPluginFormatId = parserPluginMetadata?.format.id;

  if (!isNonEmptyString(sourceInput)) {
    failures.push('malformed manifest: source.input must be a non-empty string');
  }

  if (!isNonEmptyString(sourceType) || !SOURCE_DOCS_SOURCE_TYPES.has(sourceType)) {
    failures.push('malformed manifest: source.type must be file or directory');
  }

  if (hasParserPluginMetadata && preset !== undefined) {
    failures.push('malformed manifest: parser.plugin source manifests must not include preset');
  }

  if (hasParserPluginMetadata && semanticChunkIndexes !== undefined) {
    failures.push(
      'malformed manifest: parser.plugin source manifests must not include semanticChunkIndexes'
    );
  }

  if (!isNonEmptyString(sourceFormatHint)) {
    failures.push('malformed manifest: source.formatHint must be a supported source format hint');
  } else if (hasParserPluginMetadata) {
    if (parserPluginFormatId !== undefined && sourceFormatHint !== parserPluginFormatId) {
      failures.push('malformed manifest: source.formatHint must match parser.plugin.format.id');
    }
  } else if (!SOURCE_DOCS_FORMAT_HINTS.has(sourceFormatHint)) {
    failures.push('malformed manifest: source.formatHint must be a supported source format hint');
  }

  if (!isNonEmptyString(sourceResolvedFormat)) {
    failures.push('malformed manifest: source.resolvedFormat must be a supported source format');
  } else if (hasParserPluginMetadata) {
    if (parserPluginFormatId !== undefined && sourceResolvedFormat !== parserPluginFormatId) {
      failures.push('malformed manifest: source.resolvedFormat must match parser.plugin.format.id');
    }
  } else if (!SOURCE_DOCS_RESOLVED_FORMATS.has(sourceResolvedFormat)) {
    failures.push('malformed manifest: source.resolvedFormat must be a supported source format');
  }

  validateSourceDocsParserMetadata(
    parserRecord,
    sourceResolvedFormat,
    parserPluginFormatId,
    failures
  );
  validateSourceDocsFormatterMetadata(formatterRecord, failures);

  if (!isNonEmptyString(sourcePath)) {
    failures.push('malformed manifest: source.resolvedPath must be a non-empty string');
  } else if (!isAbsolute(sourcePath)) {
    failures.push('malformed manifest: source.resolvedPath must be absolute');
  }

  if (sourceType === 'file') {
    if (!isNonNegativeInteger(sourceByteSize)) {
      failures.push('malformed manifest: source.byteSize must be a non-negative integer');
    }

    if (!isSha256Hash(sourceHash)) {
      failures.push('malformed manifest: source.hash must be a sha256 hash');
    }
  }

  if (sourceType === 'directory') {
    if (!isNonNegativeInteger(sourceFileCount)) {
      failures.push('malformed manifest: source.fileCount must be a non-negative integer');
    }

    if (!isSha256Hash(sourceAggregateHash)) {
      failures.push('malformed manifest: source.aggregateHash must be a sha256 hash');
    }
  }

  if (
    isNonEmptyString(sourcePath) &&
    isAbsolute(sourcePath) &&
    isSourceDocsSourceType(sourceType)
  ) {
    pathTypeChecks.push({
      label: 'source',
      path: sourcePath,
      expectedType: sourceType,
    });
  }

  const sourceFileEntries = validateSourceFiles({
    sourceFiles: sourceFileRecords,
    sourcePath,
    sourceType,
    sourceResolvedFormat,
    failures,
    fileChecks,
  });

  if (sourceType === 'file' && sourceFileEntries.length !== 1) {
    failures.push(
      'malformed manifest: file source manifests must contain exactly one sourceFiles entry'
    );
  }

  if (
    sourceType === 'file' &&
    sourceFileEntries.length === 1 &&
    isNonNegativeInteger(sourceByteSize) &&
    isSha256Hash(sourceHash)
  ) {
    const sourceFile = sourceFileEntries[0];

    if (sourceFile !== undefined && sourceFile.byteSize !== sourceByteSize) {
      failures.push('malformed manifest: source.byteSize must match sourceFiles[0].byteSize');
    }

    if (sourceFile !== undefined && sourceFile.hash !== sourceHash) {
      failures.push('malformed manifest: source.hash must match sourceFiles[0].hash');
    }
  }

  if (
    sourceType === 'directory' &&
    isNonNegativeInteger(sourceFileCount) &&
    sourceFileCount !== sourceFileEntries.length
  ) {
    failures.push('malformed manifest: source.fileCount must match sourceFiles length');
  }

  if (
    sourceType === 'directory' &&
    isSha256Hash(sourceAggregateHash) &&
    sourceFileEntries.length === sourceFileRecords.length
  ) {
    const actualAggregateHash = aggregateSourceFilesHash(sourceFileEntries);

    if (sourceAggregateHash !== actualAggregateHash) {
      failures.push('malformed manifest: source.aggregateHash must match sourceFiles metadata');
    }
  }

  if (
    hasParserPluginMetadata &&
    sourceType === 'directory' &&
    parserPluginMetadata !== undefined &&
    parserPluginMetadata.format.directorySupport !== true
  ) {
    failures.push(
      'malformed manifest: parser.plugin directory source manifests require parser.plugin.format.directorySupport true'
    );
  }

  validateGeneratedOutputs({
    generatedOutputs: outputRecords,
    manifestDir,
    failures,
    fileChecks,
    requireTextMetadata: true,
    rejectSymlinks: true,
    allowedKinds: SOURCE_DOCS_GENERATED_OUTPUT_KINDS,
  });
  if (hasParserPluginMetadata) {
    validateSourceDocsParserPluginGeneratedOutputs(outputRecords, failures);
  }
  const semanticChunkIndexEntries = validateSourceDocsSemanticChunkIndexes({
    semanticChunkIndexes,
    generatedOutputs: outputRecords,
    manifestDir,
    failures,
  });
  validateSourceDocsPresetMetadata(preset, failures);

  validateRequiredManifestContract(manifest.manifestContract, SOURCE_DOCS_MODE, failures);
  validateRequiredInputProvenance(manifest.inputProvenance, SOURCE_DOCS_MODE, manifest, failures);
  validateRequiredArtifactSummary(manifest.artifactSummary, SOURCE_DOCS_MODE, manifest, failures);

  if (failures.length === 0 && parserPluginMetadata !== undefined) {
    await verifySourceDocsParserPluginManifestMetadata(parserPluginMetadata, failures);
  }

  if (failures.length === 0) {
    for (const check of pathTypeChecks) {
      await verifyPathType(check, failures);
    }
  }

  const checkedFiles = failures.length === 0 ? fileChecks.length : 0;

  if (failures.length === 0) {
    for (const check of fileChecks) {
      await verifyFile(check, failures);
    }
  }

  if (failures.length === 0) {
    await verifySourceDocsSemanticChunkIndexes({
      manifestDir,
      semanticChunkIndexes: semanticChunkIndexEntries,
      failures,
    });
  }

  return {
    manifestPath,
    checkedFiles,
    failures,
  };
}
interface SourceDocsParserPluginRecord {
  manifestPath: string;
  resolvedManifestPath: string;
  manifestByteSize: number;
  manifestHash: string;
  name: string;
  version: string;
  module: {
    path: string;
    resolvedPath: string;
  };
  format: ParserPluginFormatMetadata;
}
function validateSourceDocsParserMetadata(
  parser: Record<string, unknown>,
  sourceResolvedFormat: unknown,
  parserPluginFormatId: string | undefined,
  failures: string[]
): void {
  const parserFormat = parser.format;

  if (!isNonEmptyString(parser.name)) {
    failures.push('malformed manifest: parser.name must be a non-empty string');
  }

  if (!isNonEmptyString(parser.version)) {
    failures.push('malformed manifest: parser.version must be a non-empty string');
  }

  if (!isNonEmptyString(parserFormat)) {
    failures.push('malformed manifest: parser.format must be a supported source format');
    return;
  }

  if (parserPluginFormatId === undefined && !SOURCE_DOCS_RESOLVED_FORMATS.has(parserFormat)) {
    failures.push('malformed manifest: parser.format must be a supported source format');
    return;
  }

  if (parserPluginFormatId !== undefined && parserFormat !== parserPluginFormatId) {
    failures.push('malformed manifest: parser.format must match parser.plugin.format.id');
  }

  if (isNonEmptyString(sourceResolvedFormat) && parserFormat !== sourceResolvedFormat) {
    failures.push('malformed manifest: parser.format must match source.resolvedFormat');
  }
}
function validateSourceDocsParserPluginMetadata(
  plugin: unknown,
  failures: string[],
  fileChecks: FileCheck[]
): SourceDocsParserPluginRecord | undefined {
  if (plugin === undefined) {
    return undefined;
  }

  if (!isObjectRecord(plugin)) {
    failures.push('malformed manifest: parser.plugin must be an object when present');
    return undefined;
  }

  const manifestPath = plugin.manifestPath;
  const resolvedManifestPath = plugin.resolvedManifestPath;
  const manifestByteSize = plugin.manifestByteSize;
  const manifestHash = plugin.manifestHash;
  const moduleMetadata = plugin.module;
  const formatMetadata = plugin.format;
  const execution = plugin.execution;

  if (!isNonEmptyString(manifestPath)) {
    failures.push('malformed manifest: parser.plugin.manifestPath must be a non-empty string');
  }

  if (!isNonEmptyString(resolvedManifestPath)) {
    failures.push(
      'malformed manifest: parser.plugin.resolvedManifestPath must be a non-empty string'
    );
  } else if (!isAbsolute(resolvedManifestPath)) {
    failures.push('malformed manifest: parser.plugin.resolvedManifestPath must be absolute');
  }

  if (!isNonNegativeInteger(manifestByteSize)) {
    failures.push(
      'malformed manifest: parser.plugin.manifestByteSize must be a non-negative integer'
    );
  }

  if (!isSha256Hash(manifestHash)) {
    failures.push('malformed manifest: parser.plugin.manifestHash must be a sha256 hash');
  }

  if (!isNonEmptyString(plugin.name)) {
    failures.push('malformed manifest: parser.plugin.name must be a non-empty string');
  }

  if (!isNonEmptyString(plugin.version)) {
    failures.push('malformed manifest: parser.plugin.version must be a non-empty string');
  }

  const moduleRecord = validateSourceDocsParserPluginModuleMetadata(moduleMetadata, failures);
  const formatRecord = validateSourceDocsParserPluginFormatMetadata(formatMetadata, failures);
  validateSourceDocsParserPluginExecutionMetadata(execution, failures);

  if (
    isNonEmptyString(resolvedManifestPath) &&
    isAbsolute(resolvedManifestPath) &&
    isNonNegativeInteger(manifestByteSize) &&
    isSha256Hash(manifestHash)
  ) {
    fileChecks.push({
      label: 'parser.plugin.manifest',
      path: resolvedManifestPath,
      expectedByteSize: manifestByteSize,
      expectedHash: manifestHash,
    });
  }

  if (
    !isNonEmptyString(manifestPath) ||
    !isNonEmptyString(resolvedManifestPath) ||
    !isAbsolute(resolvedManifestPath) ||
    !isNonNegativeInteger(manifestByteSize) ||
    !isSha256Hash(manifestHash) ||
    !isNonEmptyString(plugin.name) ||
    !isNonEmptyString(plugin.version) ||
    moduleRecord === undefined ||
    formatRecord === undefined
  ) {
    return undefined;
  }

  return {
    manifestPath,
    resolvedManifestPath,
    manifestByteSize,
    manifestHash,
    name: plugin.name,
    version: plugin.version,
    module: moduleRecord,
    format: formatRecord,
  };
}
function validateSourceDocsParserPluginModuleMetadata(
  moduleMetadata: unknown,
  failures: string[]
): SourceDocsParserPluginRecord['module'] | undefined {
  if (!isObjectRecord(moduleMetadata)) {
    failures.push('malformed manifest: parser.plugin.module must be an object');
    return undefined;
  }

  const modulePath = moduleMetadata.path;
  const moduleResolvedPath = moduleMetadata.resolvedPath;
  let valid = true;

  if (!isNonEmptyString(modulePath)) {
    failures.push('malformed manifest: parser.plugin.module.path must be a non-empty string');
    valid = false;
  } else if (
    isUrlLikePath(modulePath) ||
    isAbsolute(modulePath) ||
    win32.isAbsolute(modulePath) ||
    hasEmptyOrParentPathSegment(modulePath)
  ) {
    failures.push('malformed manifest: parser.plugin.module.path must be relative');
    valid = false;
  }

  if (!isNonEmptyString(moduleResolvedPath)) {
    failures.push(
      'malformed manifest: parser.plugin.module.resolvedPath must be a non-empty string'
    );
    valid = false;
  } else if (!isAbsolute(moduleResolvedPath)) {
    failures.push('malformed manifest: parser.plugin.module.resolvedPath must be absolute');
    valid = false;
  }

  return valid && isNonEmptyString(modulePath) && isNonEmptyString(moduleResolvedPath)
    ? {
        path: modulePath,
        resolvedPath: moduleResolvedPath,
      }
    : undefined;
}
function validateSourceDocsParserPluginFormatMetadata(
  formatMetadata: unknown,
  failures: string[]
): ParserPluginFormatMetadata | undefined {
  if (!isObjectRecord(formatMetadata)) {
    failures.push('malformed manifest: parser.plugin.format must be an object');
    return undefined;
  }

  const formatId = formatMetadata.id;
  const extensions = formatMetadata.extensions;
  const mediaTypes = formatMetadata.mediaTypes;
  const directorySupport = formatMetadata.directorySupport;
  let valid = true;

  if (!isNonEmptyString(formatId) || !SOURCE_DOCS_PLUGIN_FORMAT_ID_PATTERN.test(formatId)) {
    failures.push("malformed manifest: parser.plugin.format.id must match '^[a-z][a-z0-9-]*$'");
    valid = false;
  }

  if (!isNonEmptyString(formatMetadata.displayName)) {
    failures.push(
      'malformed manifest: parser.plugin.format.displayName must be a non-empty string'
    );
    valid = false;
  }

  if (!Array.isArray(extensions) || extensions.length === 0) {
    failures.push('malformed manifest: parser.plugin.format.extensions must be a non-empty array');
    valid = false;
  } else if (!extensions.every((extension) => isNonEmptyString(extension))) {
    failures.push('malformed manifest: parser.plugin.format.extensions must contain only strings');
    valid = false;
  }

  let parsedMediaTypes: string[] | undefined;
  if (mediaTypes !== undefined) {
    parsedMediaTypes = validateOptionalStringArray(
      mediaTypes,
      'parser.plugin.format.mediaTypes',
      failures
    );

    if (parsedMediaTypes === undefined) {
      valid = false;
    }

    if (parsedMediaTypes?.some((mediaType) => mediaType.length === 0)) {
      failures.push(
        'malformed manifest: parser.plugin.format.mediaTypes must contain only non-empty strings'
      );
      valid = false;
    }
  }

  if (directorySupport !== undefined && typeof directorySupport !== 'boolean') {
    failures.push('malformed manifest: parser.plugin.format.directorySupport must be a boolean');
    valid = false;
  }

  return valid &&
    isNonEmptyString(formatId) &&
    SOURCE_DOCS_PLUGIN_FORMAT_ID_PATTERN.test(formatId) &&
    isNonEmptyString(formatMetadata.displayName) &&
    Array.isArray(extensions) &&
    extensions.length > 0 &&
    extensions.every((extension) => isNonEmptyString(extension))
    ? {
        id: formatId,
        displayName: formatMetadata.displayName,
        extensions,
        ...(parsedMediaTypes === undefined ? {} : { mediaTypes: parsedMediaTypes }),
        ...(typeof directorySupport === 'boolean' ? { directorySupport } : {}),
      }
    : undefined;
}
function validateSourceDocsParserPluginExecutionMetadata(
  execution: unknown,
  failures: string[]
): void {
  if (!isObjectRecord(execution)) {
    failures.push('malformed manifest: parser.plugin.execution must be an object');
    return;
  }

  if (execution.codeExecuted !== true) {
    failures.push('malformed manifest: parser.plugin.execution.codeExecuted must be true');
  }

  if (execution.trust !== 'trusted-local-code') {
    failures.push("malformed manifest: parser.plugin.execution.trust must be 'trusted-local-code'");
  }

  if (execution.sandboxed !== false) {
    failures.push('malformed manifest: parser.plugin.execution.sandboxed must be false');
  }

  if (!isNonEmptyString(execution.statement)) {
    failures.push(
      'malformed manifest: parser.plugin.execution.statement must be a non-empty string'
    );
  }
}
function validateSourceDocsParserPluginGeneratedOutputs(
  generatedOutputs: unknown[],
  failures: string[]
): void {
  for (const [index, output] of generatedOutputs.entries()) {
    if (!isObjectRecord(output)) {
      continue;
    }

    if (output.kind === SOURCE_DOCS_SEMANTIC_CHUNK_JSONL_KIND) {
      failures.push(
        `malformed manifest: generatedOutputs[${index}].kind must not be semantic-chunks-jsonl for parser.plugin source manifests`
      );
    }
  }
}
async function verifySourceDocsParserPluginManifestMetadata(
  recorded: SourceDocsParserPluginRecord,
  failures: string[]
): Promise<void> {
  try {
    const actualManifestFile = await describeFile(recorded.resolvedManifestPath);

    if (actualManifestFile.byteSize !== recorded.manifestByteSize) {
      failures.push(
        'parser.plugin.manifest: byte size does not match parser.plugin.manifestByteSize'
      );
    }

    if (actualManifestFile.hash !== recorded.manifestHash) {
      failures.push('parser.plugin.manifest: hash does not match parser.plugin.manifestHash');
    }
  } catch (error) {
    if (isFileNotFoundError(error)) {
      failures.push(`parser.plugin.manifest: missing file at ${recorded.resolvedManifestPath}`);
      return;
    }

    failures.push(
      `parser.plugin.manifest: cannot read ${recorded.resolvedManifestPath}: ${errorMessage(error)}`
    );
    return;
  }

  const validation = await validateParserPluginManifestFile({
    manifestPath: recorded.resolvedManifestPath,
  });

  if (!validation.valid || validation.manifest === undefined) {
    const details = validation.errors.map((error) => `${error.path}: ${error.message}`).join('; ');

    failures.push(`parser.plugin.manifest: recorded plugin manifest is invalid: ${details}`);
    return;
  }

  compareParserPluginManifestMetadata(recorded, validation.manifest, failures);
}
function compareParserPluginManifestMetadata(
  recorded: SourceDocsParserPluginRecord,
  manifest: ParserPluginManifestMetadata,
  failures: string[]
): void {
  if (recorded.name !== manifest.name) {
    failures.push('parser.plugin.name must match parser plugin manifest name');
  }

  if (recorded.version !== manifest.version) {
    failures.push('parser.plugin.version must match parser plugin manifest version');
  }

  if (recorded.module.path !== manifest.module) {
    failures.push('parser.plugin.module.path must match parser plugin manifest module');
  }

  const selectedFormat = manifest.formats.find((format) => format.id === recorded.format.id);

  if (selectedFormat === undefined) {
    failures.push('parser.plugin.format.id must match a format declared by the plugin manifest');
    return;
  }

  compareParserPluginFormatMetadata(recorded.format, selectedFormat, failures);
}
function compareParserPluginFormatMetadata(
  recorded: ParserPluginFormatMetadata,
  selectedFormat: ParserPluginFormatMetadata,
  failures: string[]
): void {
  if (recorded.displayName !== selectedFormat.displayName) {
    failures.push(
      'parser.plugin.format.displayName must match parser plugin manifest selected format'
    );
  }

  if (!stringArraysEqual(recorded.extensions, selectedFormat.extensions)) {
    failures.push(
      'parser.plugin.format.extensions must match parser plugin manifest selected format'
    );
  }

  if (!optionalStringArraysEqual(recorded.mediaTypes, selectedFormat.mediaTypes)) {
    failures.push(
      'parser.plugin.format.mediaTypes must match parser plugin manifest selected format'
    );
  }

  if (recorded.directorySupport !== selectedFormat.directorySupport) {
    failures.push(
      'parser.plugin.format.directorySupport must match parser plugin manifest selected format'
    );
  }
}
function validateSourceDocsFormatterMetadata(
  formatter: Record<string, unknown>,
  failures: string[]
): void {
  if (formatter.name !== SOURCE_DOCS_FORMATTER_NAME) {
    failures.push(`malformed manifest: formatter.name must be ${SOURCE_DOCS_FORMATTER_NAME}`);
  }

  if (!isNonEmptyString(formatter.version)) {
    failures.push('malformed manifest: formatter.version must be a non-empty string');
  }

  if (formatter.format !== SOURCE_DOCS_FORMATTER_FORMAT) {
    failures.push(`malformed manifest: formatter.format must be ${SOURCE_DOCS_FORMATTER_FORMAT}`);
  }
}
function validateSourceDocsSemanticChunkIndexes(options: {
  semanticChunkIndexes: unknown;
  generatedOutputs: unknown[];
  manifestDir: string;
  failures: string[];
}): SemanticChunkManifestIndex[] {
  const { semanticChunkIndexes, generatedOutputs, manifestDir, failures } = options;

  if (semanticChunkIndexes === undefined) {
    // A semantic-chunks-jsonl output with no index would leave its chunk
    // metadata (ordinals, per-chunk hashes, warning counts) unverified, so an
    // omitted index must fail rather than silently pass when such an output
    // exists.
    if (sourceDocsSemanticChunkOutputPaths(generatedOutputs, manifestDir).size > 0) {
      failures.push(
        'malformed manifest: semanticChunkIndexes is required when a semantic-chunks-jsonl output is present'
      );
    }
    return [];
  }

  if (!Array.isArray(semanticChunkIndexes)) {
    failures.push('malformed manifest: semanticChunkIndexes must be an array when present');
    return [];
  }

  const expectedChunkOutputPaths = sourceDocsSemanticChunkOutputPaths(
    generatedOutputs,
    manifestDir
  );
  const entries: SemanticChunkManifestIndex[] = [];
  const seenPaths = new Set<string>();

  for (const [index, chunkIndex] of semanticChunkIndexes.entries()) {
    const label = `semanticChunkIndexes[${index}]`;

    if (!isObjectRecord(chunkIndex)) {
      failures.push(`malformed manifest: ${label} must be an object`);
      continue;
    }

    validateAllowedKeys(chunkIndex, SOURCE_DOCS_SEMANTIC_CHUNK_INDEX_KEYS, label, failures);

    const outputPath = chunkIndex.path;
    const format = chunkIndex.format;
    const chunkCount = chunkIndex.chunkCount;
    const aggregateHash = chunkIndex.aggregateHash;
    const warningCount = chunkIndex.warningCount;
    const chunks = chunkIndex.chunks;
    const chunkEntries: SemanticChunkManifestIndexChunk[] = [];

    if (!isNonEmptyString(outputPath)) {
      failures.push(`malformed manifest: ${label}.path must be a non-empty string`);
    } else if (isAbsolute(outputPath)) {
      failures.push(`malformed manifest: ${label}.path must be relative: ${outputPath}`);
    } else if (!isInsideDirectory(manifestDir, resolve(manifestDir, outputPath))) {
      failures.push(`malformed manifest: ${label}.path escapes manifest directory: ${outputPath}`);
    } else if (!expectedChunkOutputPaths.has(outputPath)) {
      failures.push(
        `malformed manifest: ${label}.path must reference a semantic-chunks-jsonl generated output`
      );
    } else if (seenPaths.has(outputPath)) {
      failures.push(`malformed manifest: duplicate semantic chunk index path: ${outputPath}`);
    } else {
      seenPaths.add(outputPath);
    }

    if (format !== 'jsonl') {
      failures.push(`malformed manifest: ${label}.format must be jsonl`);
    }

    if (!isNonNegativeInteger(chunkCount)) {
      failures.push(`malformed manifest: ${label}.chunkCount must be a non-negative integer`);
    }

    if (!isSha256Hash(aggregateHash)) {
      failures.push(`malformed manifest: ${label}.aggregateHash must be a sha256 hash`);
    }

    if (!isNonNegativeInteger(warningCount)) {
      failures.push(`malformed manifest: ${label}.warningCount must be a non-negative integer`);
    }

    if (!Array.isArray(chunks)) {
      failures.push(`malformed manifest: ${label}.chunks must be an array`);
    } else {
      for (const [chunkEntryIndex, chunkEntry] of chunks.entries()) {
        const chunkLabel = `${label}.chunks[${chunkEntryIndex}]`;
        const normalizedChunk = validateSourceDocsSemanticChunkIndexChunk({
          chunkEntry,
          label: chunkLabel,
          expectedOrder: chunkEntryIndex + 1,
          failures,
        });

        if (normalizedChunk !== undefined) {
          chunkEntries.push(normalizedChunk);
        }
      }
    }

    if (Array.isArray(chunks) && isNonNegativeInteger(chunkCount) && chunks.length !== chunkCount) {
      failures.push(`malformed manifest: ${label}.chunkCount must match chunks length`);
    }

    if (
      isNonNegativeInteger(warningCount) &&
      Array.isArray(chunks) &&
      chunkEntries.length === chunks.length
    ) {
      const actualWarningCount = chunkEntries.reduce(
        (total, chunk) => total + chunk.warningCount,
        0
      );

      if (warningCount !== actualWarningCount) {
        failures.push(`malformed manifest: ${label}.warningCount must match chunk warning counts`);
      }
    }

    if (
      isNonEmptyString(outputPath) &&
      !isAbsolute(outputPath) &&
      isInsideDirectory(manifestDir, resolve(manifestDir, outputPath)) &&
      format === 'jsonl' &&
      isNonNegativeInteger(chunkCount) &&
      isSha256Hash(aggregateHash) &&
      isNonNegativeInteger(warningCount) &&
      Array.isArray(chunks) &&
      chunkEntries.length === chunks.length
    ) {
      const normalizedIndex: SemanticChunkManifestIndex = {
        path: outputPath,
        format,
        chunkCount,
        aggregateHash,
        warningCount,
        chunks: chunkEntries,
      };
      const actualAggregateHash = hashSemanticChunkManifestIndex({
        path: normalizedIndex.path,
        format: normalizedIndex.format,
        chunkCount: normalizedIndex.chunkCount,
        warningCount: normalizedIndex.warningCount,
        chunks: normalizedIndex.chunks,
      });

      if (normalizedIndex.aggregateHash !== actualAggregateHash) {
        failures.push(
          `malformed manifest: ${label}.aggregateHash must match semantic chunk index metadata`
        );
      }

      entries.push(normalizedIndex);
    }
  }

  if (
    semanticChunkIndexes.length === entries.length &&
    expectedChunkOutputPaths.size !== entries.length
  ) {
    failures.push(
      'malformed manifest: semanticChunkIndexes must contain one entry per semantic-chunks-jsonl generated output'
    );
  }

  return entries;
}
function validateSourceDocsSemanticChunkIndexChunk(options: {
  chunkEntry: unknown;
  label: string;
  expectedOrder: number;
  failures: string[];
}): SemanticChunkManifestIndexChunk | undefined {
  const { chunkEntry, label, expectedOrder, failures } = options;

  if (!isObjectRecord(chunkEntry)) {
    failures.push(`malformed manifest: ${label} must be an object`);
    return undefined;
  }

  validateAllowedKeys(chunkEntry, SOURCE_DOCS_SEMANTIC_CHUNK_INDEX_CHUNK_KEYS, label, failures);

  const id = chunkEntry.id;
  const order = chunkEntry.order;
  const title = chunkEntry.title;
  const path = chunkEntry.path;
  const nodePath = chunkEntry.nodePath;
  const contentHash = chunkEntry.contentHash;
  const characterCount = chunkEntry.characterCount;
  const estimatedTokenCount = chunkEntry.estimatedTokenCount;
  const sourceFormat = chunkEntry.sourceFormat;
  const sourcePath = chunkEntry.sourcePath;
  const warningCount = chunkEntry.warningCount;

  if (!isNonEmptyString(id)) {
    failures.push(`malformed manifest: ${label}.id must be a non-empty string`);
  }

  if (!isPositiveInteger(order)) {
    failures.push(`malformed manifest: ${label}.order must be a positive integer`);
  } else if (order !== expectedOrder) {
    failures.push(`malformed manifest: ${label}.order must match chunk index order`);
  }

  if (!isNonEmptyString(title)) {
    failures.push(`malformed manifest: ${label}.title must be a non-empty string`);
  }

  if (!isStringArray(path)) {
    failures.push(`malformed manifest: ${label}.path must be a string array`);
  }

  if (!isStringArray(nodePath)) {
    failures.push(`malformed manifest: ${label}.nodePath must be a string array`);
  }

  if (!isUnprefixedSha256Hash(contentHash)) {
    failures.push(`malformed manifest: ${label}.contentHash must be a sha256 hex digest`);
  }

  if (!isNonNegativeInteger(characterCount)) {
    failures.push(`malformed manifest: ${label}.characterCount must be a non-negative integer`);
  }

  if (!isNonNegativeInteger(estimatedTokenCount)) {
    failures.push(
      `malformed manifest: ${label}.estimatedTokenCount must be a non-negative integer`
    );
  }

  if ('sourceFormat' in chunkEntry && !isNonEmptyString(sourceFormat)) {
    failures.push(`malformed manifest: ${label}.sourceFormat must be a non-empty string`);
  }

  if ('sourcePath' in chunkEntry && !isNonEmptyString(sourcePath)) {
    failures.push(`malformed manifest: ${label}.sourcePath must be a non-empty string`);
  }

  if (!isNonNegativeInteger(warningCount)) {
    failures.push(`malformed manifest: ${label}.warningCount must be a non-negative integer`);
  }

  if (
    !isNonEmptyString(id) ||
    !isPositiveInteger(order) ||
    !isNonEmptyString(title) ||
    !isStringArray(path) ||
    !isStringArray(nodePath) ||
    !isUnprefixedSha256Hash(contentHash) ||
    !isNonNegativeInteger(characterCount) ||
    !isNonNegativeInteger(estimatedTokenCount) ||
    ('sourceFormat' in chunkEntry && !isNonEmptyString(sourceFormat)) ||
    ('sourcePath' in chunkEntry && !isNonEmptyString(sourcePath)) ||
    !isNonNegativeInteger(warningCount)
  ) {
    return undefined;
  }

  const normalizedChunk: SemanticChunkManifestIndexChunk = {
    id,
    order,
    title,
    path,
    nodePath,
    contentHash,
    characterCount,
    estimatedTokenCount,
    warningCount,
  };

  if (typeof sourceFormat === 'string') {
    normalizedChunk.sourceFormat = sourceFormat;
  }

  if (typeof sourcePath === 'string') {
    normalizedChunk.sourcePath = sourcePath;
  }

  return normalizedChunk;
}
async function verifySourceDocsSemanticChunkIndexes(options: {
  manifestDir: string;
  semanticChunkIndexes: SemanticChunkManifestIndex[];
  failures: string[];
}): Promise<void> {
  for (const semanticChunkIndex of options.semanticChunkIndexes) {
    let actualIndex: SemanticChunkManifestIndex;

    try {
      actualIndex = await buildSemanticChunkJsonlManifestIndex({
        manifestDir: options.manifestDir,
        outputPath: semanticChunkIndex.path,
      });
    } catch (error) {
      options.failures.push(
        `semantic chunk index ${semanticChunkIndex.path}: ${errorMessage(error)}`
      );
      continue;
    }

    if (!semanticChunkManifestIndexesEqual(semanticChunkIndex, actualIndex)) {
      options.failures.push(
        `semantic chunk index ${semanticChunkIndex.path}: manifest metadata does not match JSONL records`
      );
    }
  }
}
function sourceDocsSemanticChunkOutputPaths(
  generatedOutputs: unknown[],
  manifestDir: string
): Set<string> {
  const paths = new Set<string>();

  for (const output of generatedOutputs) {
    if (!isObjectRecord(output) || output.kind !== SOURCE_DOCS_SEMANTIC_CHUNK_JSONL_KIND) {
      continue;
    }

    const outputPath = output.path;

    if (
      isNonEmptyString(outputPath) &&
      !isAbsolute(outputPath) &&
      isInsideDirectory(manifestDir, resolve(manifestDir, outputPath))
    ) {
      paths.add(outputPath);
    }
  }

  return paths;
}
function validateSourceDocsPresetMetadata(preset: unknown, failures: string[]): void {
  for (const failure of validateSourceDocsPresetContract(preset)) {
    failures.push(`malformed manifest: ${failure}`);
  }
}

export function validateSourceDocsPresetContract(preset: unknown): string[] {
  const failures: string[] = [];

  if (preset === undefined) {
    return failures;
  }

  if (!isObjectRecord(preset)) {
    failures.push('preset must be an object when present');
    return failures;
  }

  if (preset.name !== SOURCE_DOCS_SWIFT_BOOK_PRESET_NAME) {
    failures.push(`preset.name must be ${SOURCE_DOCS_SWIFT_BOOK_PRESET_NAME}`);
  }

  if (!isNonEmptyString(preset.configPath)) {
    failures.push('preset.configPath must be a non-empty string');
  }

  if (!isNonEmptyString(preset.displayName)) {
    failures.push('preset.displayName must be a non-empty string');
  }

  const defaults = preset.defaults;
  if (!isObjectRecord(defaults)) {
    failures.push('preset.defaults must be an object');
  } else {
    if (defaults.format !== 'markdown') {
      failures.push('preset.defaults.format must be markdown');
    }

    if (!isNonEmptyString(defaults.filenamePrefix)) {
      failures.push('preset.defaults.filenamePrefix must be a non-empty string');
    }

    if (!isNonEmptyString(defaults.title)) {
      failures.push('preset.defaults.title must be a non-empty string');
    }

    if (!isNonEmptyString(defaults.systemPrompt)) {
      failures.push('preset.defaults.systemPrompt must be a non-empty string');
    } else {
      const unsupportedPromptClaims = findUnsupportedPresetPromptClaims(defaults.systemPrompt);

      if (unsupportedPromptClaims.length > 0) {
        failures.push(
          `preset.defaults.systemPrompt must not claim ${formatAllowedOutputKinds(new Set(unsupportedPromptClaims))}`
        );
      }
    }

    if (
      'outputFormats' in defaults &&
      (!Array.isArray(defaults.outputFormats) ||
        !defaults.outputFormats.every((format) => isNonEmptyString(format)))
    ) {
      failures.push(
        'preset.defaults.outputFormats must be an array of non-empty strings when present'
      );
    }
  }

  const metadata = preset.metadata;
  if (!isObjectRecord(metadata)) {
    failures.push('preset.metadata must be an object');
  } else {
    for (const [field, expectedValue] of Object.entries(SOURCE_DOCS_SWIFT_BOOK_PRESET_METADATA)) {
      if (metadata[field] !== expectedValue) {
        failures.push(`preset.metadata.${field} must be ${expectedValue}`);
      }
    }
  }

  if (!Array.isArray(preset.limitations)) {
    failures.push('preset.limitations must be an array');
    return failures;
  }

  if (!preset.limitations.every((limitation) => isNonEmptyString(limitation))) {
    failures.push('preset.limitations must contain only non-empty strings');
    return failures;
  }

  for (const limitation of SOURCE_DOCS_SWIFT_BOOK_PRESET_LIMITATIONS) {
    if (!preset.limitations.includes(limitation)) {
      failures.push(`preset.limitations must include "${limitation}"`);
    }
  }

  return failures;
}
function findUnsupportedPresetPromptClaims(prompt: string): string[] {
  const normalizedPrompt = prompt.toLowerCase().replace(/[-_]+/g, ' ').replace(/\s+/g, ' ').trim();
  const claims: string[] = [];

  if (/\b(complete|completeness|comprehensive)\b/.test(normalizedPrompt)) {
    claims.push('completeness');
  }

  if (/\bsource truth\b/.test(normalizedPrompt)) {
    claims.push('source truth');
  }

  if (/\b(verified|verification|validated|validation)\b/.test(normalizedPrompt)) {
    claims.push('source verification');
  }

  if (/\b(authoritative|authority|official)\b/.test(normalizedPrompt)) {
    claims.push('authority or official status');
  }

  return claims;
}
interface SourceFileEntry {
  path: string;
  resolvedPath: string;
  byteSize: number;
  hash: string;
  format: string;
}
function validateSourceFiles(options: {
  sourceFiles: unknown[];
  sourcePath: unknown;
  sourceType: unknown;
  sourceResolvedFormat: unknown;
  failures: string[];
  fileChecks: FileCheck[];
}): SourceFileEntry[] {
  const { sourceFiles, sourcePath, sourceType, sourceResolvedFormat, failures, fileChecks } =
    options;
  const sourceFileEntries: SourceFileEntry[] = [];
  const sourceRoot =
    isNonEmptyString(sourcePath) && isAbsolute(sourcePath) ? sourcePath : undefined;
  const trustedRoot =
    sourceRoot === undefined
      ? undefined
      : sourceType === 'directory'
        ? sourceRoot
        : dirname(sourceRoot);

  for (const [index, sourceFile] of sourceFiles.entries()) {
    const label = `sourceFiles[${index}]`;

    if (!isObjectRecord(sourceFile)) {
      failures.push(`malformed manifest: ${label} must be an object`);
      continue;
    }

    const sourceFilePath = sourceFile.path;
    const sourceFileResolvedPath = sourceFile.resolvedPath;
    const sourceFileByteSize = sourceFile.byteSize;
    const sourceFileHash = sourceFile.hash;
    const sourceFileLineCount = sourceFile.lineCount;
    const sourceFileEstimatedTokenCount = sourceFile.estimatedTokenCount;
    const sourceFileFormat = sourceFile.format;

    if (!isNonEmptyString(sourceFilePath)) {
      failures.push(`malformed manifest: ${label}.path must be a non-empty string`);
    } else if (isAbsolute(sourceFilePath)) {
      failures.push(`malformed manifest: ${label}.path must be relative: ${sourceFilePath}`);
    } else if (
      sourceRoot !== undefined &&
      sourceType === 'directory' &&
      !isInsideDirectory(sourceRoot, resolve(sourceRoot, sourceFilePath))
    ) {
      failures.push(`malformed manifest: ${label}.path escapes source root: ${sourceFilePath}`);
    }

    if (!isNonEmptyString(sourceFileResolvedPath)) {
      failures.push(`malformed manifest: ${label}.resolvedPath must be a non-empty string`);
    } else if (!isAbsolute(sourceFileResolvedPath)) {
      failures.push(`malformed manifest: ${label}.resolvedPath must be absolute`);
    } else if (
      sourceRoot !== undefined &&
      sourceType === 'directory' &&
      !isInsideDirectory(sourceRoot, sourceFileResolvedPath)
    ) {
      failures.push(
        `malformed manifest: ${label}.resolvedPath escapes source root: ${sourceFileResolvedPath}`
      );
    }

    if (
      sourceRoot !== undefined &&
      isNonEmptyString(sourceFilePath) &&
      !isAbsolute(sourceFilePath) &&
      isNonEmptyString(sourceFileResolvedPath) &&
      isAbsolute(sourceFileResolvedPath) &&
      isSourceDocsSourceType(sourceType)
    ) {
      const expectedResolvedPath =
        sourceType === 'directory'
          ? resolve(sourceRoot, sourceFilePath)
          : resolve(dirname(sourceRoot), sourceFilePath);

      if (expectedResolvedPath !== sourceFileResolvedPath) {
        failures.push(
          `malformed manifest: ${label}.resolvedPath must match ${label}.path under source.resolvedPath`
        );
      }

      if (sourceType === 'file' && sourceFileResolvedPath !== sourceRoot) {
        failures.push(
          `malformed manifest: ${label}.resolvedPath must match source.resolvedPath for file sources`
        );
      }
    }

    if (!isNonNegativeInteger(sourceFileByteSize)) {
      failures.push(`malformed manifest: ${label}.byteSize must be a non-negative integer`);
    }

    if (!isSha256Hash(sourceFileHash)) {
      failures.push(`malformed manifest: ${label}.hash must be a sha256 hash`);
    }

    if (!isNonNegativeInteger(sourceFileLineCount)) {
      failures.push(`malformed manifest: ${label}.lineCount must be a non-negative integer`);
    }

    if (!isNonNegativeInteger(sourceFileEstimatedTokenCount)) {
      failures.push(
        `malformed manifest: ${label}.estimatedTokenCount must be a non-negative integer`
      );
    }

    if (!isNonEmptyString(sourceFileFormat)) {
      failures.push(`malformed manifest: ${label}.format must be a non-empty string`);
    } else if (
      isNonEmptyString(sourceResolvedFormat) &&
      sourceFileFormat !== sourceResolvedFormat
    ) {
      failures.push(`malformed manifest: ${label}.format must match source.resolvedFormat`);
    }

    if (
      isNonEmptyString(sourceFilePath) &&
      !isAbsolute(sourceFilePath) &&
      isNonEmptyString(sourceFileResolvedPath) &&
      isAbsolute(sourceFileResolvedPath) &&
      isNonNegativeInteger(sourceFileByteSize) &&
      isSha256Hash(sourceFileHash) &&
      isNonEmptyString(sourceFileFormat)
    ) {
      sourceFileEntries.push({
        path: sourceFilePath,
        resolvedPath: sourceFileResolvedPath,
        byteSize: sourceFileByteSize,
        hash: sourceFileHash,
        format: sourceFileFormat,
      });
      const fileCheck: FileCheck = {
        label,
        path: sourceFileResolvedPath,
        expectedByteSize: sourceFileByteSize,
        expectedHash: sourceFileHash,
        rejectSymlink: true,
      };

      if (
        isNonNegativeInteger(sourceFileLineCount) &&
        isNonNegativeInteger(sourceFileEstimatedTokenCount)
      ) {
        fileCheck.expectedLineCount = sourceFileLineCount;
        fileCheck.expectedEstimatedTokenCount = sourceFileEstimatedTokenCount;
      }

      if (trustedRoot !== undefined) {
        fileCheck.trustedRoot = trustedRoot;
      }

      fileChecks.push(fileCheck);
    }
  }

  return sourceFileEntries;
}
